/* Generated by re2c 0.14.3 on Mon Mar 20 17:54:02 2017 */
#line 1 "bt_lexer.re"
#include "bt_lexer.h"
#include "bt_parser.h"

#define TOKEN_STRING string(start, this->_cursor - start)
#define TOKEN_STRING_LITERAL string(start + 1, this->_cursor - (start + 2))

#define UNKNOWN_TOKEN cout << "Unknown token '" << TOKEN_STRING << "' near line " << currentline << endl; \
                              continue;

#define TOKENIZE(token_type) token.value = TOKEN_STRING; \
                             token.type = token_type;    \
                             token.line = currentline;   \
                             tokens.push_back(token);    \
                             continue;

#define TOKENIZE_STRING_LITERAL(token_type) token.value = TOKEN_STRING_LITERAL; \
                                            token.type = token_type;    \
                                            token.line = currentline;   \
                                            tokens.push_back(token);    \
                                            continue;

BTLexer::BTLexer(const char* s): _cursor(s), _start(NULL), _marker(NULL)
{
}

string BTLexer::getString(const char* start, const char* end) const
{
    return string(start, end - start);
}

list<BTLexer::Token> BTLexer::lex()
{
    list<BTLexer::Token> tokens;
    unsigned int currentline = 0;

    for(; ;)
    {
        Token token;
        const char* start = this->_cursor;

        
#line 45 "bt_lexer.cpp"
{
	char yych;
	unsigned int yyaccept = 0;

	yych = *this->_cursor;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\r':
	case ' ':
	case '\\':	goto yy6;
	case '\n':	goto yy8;
	case '!':	goto yy10;
	case '"':	goto yy12;
	case '%':	goto yy13;
	case '&':	goto yy15;
	case '\'':	goto yy17;
	case '(':	goto yy18;
	case ')':	goto yy20;
	case '*':	goto yy22;
	case '+':	goto yy24;
	case ',':	goto yy26;
	case '-':	goto yy28;
	case '.':	goto yy30;
	case '/':	goto yy32;
	case '0':	goto yy34;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy36;
	case ':':	goto yy38;
	case ';':	goto yy40;
	case '<':	goto yy42;
	case '=':	goto yy44;
	case '>':	goto yy46;
	case '?':	goto yy48;
	case 'A':
	case 'E':
	case 'G':
	case 'J':
	case 'K':
	case 'M':
	case 'N':
	case 'P':
	case 'R':
	case 'T':
	case 'V':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'g':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	case 'B':	goto yy52;
	case 'C':	goto yy53;
	case 'D':	goto yy54;
	case 'F':	goto yy55;
	case 'H':	goto yy56;
	case 'I':	goto yy57;
	case 'L':	goto yy58;
	case 'O':	goto yy59;
	case 'Q':	goto yy60;
	case 'S':	goto yy61;
	case 'U':	goto yy62;
	case 'W':	goto yy63;
	case '[':	goto yy64;
	case ']':	goto yy66;
	case '^':	goto yy68;
	case '_':	goto yy70;
	case 'b':	goto yy71;
	case 'c':	goto yy72;
	case 'd':	goto yy73;
	case 'e':	goto yy74;
	case 'f':	goto yy75;
	case 'h':	goto yy76;
	case 'i':	goto yy77;
	case 'l':	goto yy78;
	case 'q':	goto yy79;
	case 'r':	goto yy80;
	case 's':	goto yy81;
	case 't':	goto yy82;
	case 'u':	goto yy83;
	case 'v':	goto yy84;
	case 'w':	goto yy85;
	case '{':	goto yy86;
	case '|':	goto yy88;
	case '}':	goto yy90;
	case '~':	goto yy92;
	default:	goto yy4;
	}
yy2:
	++this->_cursor;
#line 59 "bt_lexer.re"
	{ break; }
#line 153 "bt_lexer.cpp"
yy4:
	++this->_cursor;
yy5:
#line 169 "bt_lexer.re"
	{ UNKNOWN_TOKEN }
#line 159 "bt_lexer.cpp"
yy6:
	++this->_cursor;
	yych = *this->_cursor;
	goto yy471;
yy7:
#line 61 "bt_lexer.re"
	{ continue; }
#line 167 "bt_lexer.cpp"
yy8:
	++this->_cursor;
yy9:
#line 60 "bt_lexer.re"
	{ currentline++; continue; }
#line 173 "bt_lexer.cpp"
yy10:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy468;
	default:	goto yy11;
	}
yy11:
#line 83 "bt_lexer.re"
	{ TOKENIZE(BTT_LOG_NOT) }
#line 183 "bt_lexer.cpp"
yy12:
	yyaccept = 0;
	yych = *(this->_marker = ++this->_cursor);
	goto yy366;
yy13:
	++this->_cursor;
#line 109 "bt_lexer.re"
	{ TOKENIZE(BTT_MOD) }
#line 192 "bt_lexer.cpp"
yy15:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '&':	goto yy466;
	case '=':	goto yy464;
	default:	goto yy16;
	}
yy16:
#line 76 "bt_lexer.re"
	{ TOKENIZE(BTT_BIN_AND) }
#line 203 "bt_lexer.cpp"
yy17:
	yyaccept = 0;
	yych = *(this->_marker = ++this->_cursor);
	switch (yych) {
	case '"':	goto yy5;
	default:	goto yy371;
	}
yy18:
	++this->_cursor;
#line 63 "bt_lexer.re"
	{ TOKENIZE(BTT_O_ROUND)   }
#line 215 "bt_lexer.cpp"
yy20:
	++this->_cursor;
#line 64 "bt_lexer.re"
	{ TOKENIZE(BTT_C_ROUND)   }
#line 220 "bt_lexer.cpp"
yy22:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy462;
	default:	goto yy23;
	}
yy23:
#line 107 "bt_lexer.re"
	{ TOKENIZE(BTT_MUL) }
#line 230 "bt_lexer.cpp"
yy24:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '+':	goto yy458;
	case '=':	goto yy460;
	default:	goto yy25;
	}
yy25:
#line 105 "bt_lexer.re"
	{ TOKENIZE(BTT_ADD) }
#line 241 "bt_lexer.cpp"
yy26:
	++this->_cursor;
#line 69 "bt_lexer.re"
	{ TOKENIZE(BTT_COMMA)     }
#line 246 "bt_lexer.cpp"
yy28:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '-':	goto yy454;
	case '=':	goto yy456;
	default:	goto yy29;
	}
yy29:
#line 106 "bt_lexer.re"
	{ TOKENIZE(BTT_SUB) }
#line 257 "bt_lexer.cpp"
yy30:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy434;
	default:	goto yy31;
	}
yy31:
#line 70 "bt_lexer.re"
	{ TOKENIZE(BTT_DOT)       }
#line 276 "bt_lexer.cpp"
yy32:
	yyaccept = 1;
	yych = *(this->_marker = ++this->_cursor);
	switch (yych) {
	case '*':	goto yy447;
	case '/':	goto yy449;
	case '=':	goto yy445;
	default:	goto yy33;
	}
yy33:
#line 108 "bt_lexer.re"
	{ TOKENIZE(BTT_DIV) }
#line 289 "bt_lexer.cpp"
yy34:
	yyaccept = 2;
	yych = *(this->_marker = ++this->_cursor);
	switch (yych) {
	case '.':	goto yy434;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy438;
	case '8':
	case '9':	goto yy440;
	case 'x':	goto yy437;
	default:	goto yy35;
	}
yy35:
#line 163 "bt_lexer.re"
	{ TOKENIZE(BTT_LITERAL_OCT)                   }
#line 311 "bt_lexer.cpp"
yy36:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '.':	goto yy434;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy432;
	default:	goto yy37;
	}
yy37:
#line 164 "bt_lexer.re"
	{ TOKENIZE(BTT_LITERAL_DEC)                   }
#line 331 "bt_lexer.cpp"
yy38:
	++this->_cursor;
#line 72 "bt_lexer.re"
	{ TOKENIZE(BTT_COLON)     }
#line 336 "bt_lexer.cpp"
yy40:
	++this->_cursor;
#line 71 "bt_lexer.re"
	{ TOKENIZE(BTT_SEMICOLON) }
#line 341 "bt_lexer.cpp"
yy42:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '<':	goto yy426;
	case '=':	goto yy428;
	default:	goto yy43;
	}
yy43:
#line 87 "bt_lexer.re"
	{ TOKENIZE(BTT_LT) }
#line 352 "bt_lexer.cpp"
yy44:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy424;
	default:	goto yy45;
	}
yy45:
#line 73 "bt_lexer.re"
	{ TOKENIZE(BTT_ASSIGN)    }
#line 362 "bt_lexer.cpp"
yy46:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy420;
	case '>':	goto yy418;
	default:	goto yy47;
	}
yy47:
#line 88 "bt_lexer.re"
	{ TOKENIZE(BTT_GT) }
#line 373 "bt_lexer.cpp"
yy48:
	++this->_cursor;
#line 74 "bt_lexer.re"
	{ TOKENIZE(BTT_QUESTION)  }
#line 378 "bt_lexer.cpp"
yy50:
	++this->_cursor;
	yych = *this->_cursor;
	goto yy99;
yy51:
#line 161 "bt_lexer.re"
	{ TOKENIZE(BTT_IDENTIFIER)                    }
#line 386 "bt_lexer.cpp"
yy52:
	yych = *++this->_cursor;
	switch (yych) {
	case 'Y':	goto yy416;
	default:	goto yy99;
	}
yy53:
	yych = *++this->_cursor;
	switch (yych) {
	case 'H':	goto yy414;
	default:	goto yy99;
	}
yy54:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy396;
	case 'W':	goto yy397;
	default:	goto yy99;
	}
yy55:
	yych = *++this->_cursor;
	switch (yych) {
	case 'I':	goto yy385;
	case 'L':	goto yy386;
	default:	goto yy99;
	}
yy56:
	yych = *++this->_cursor;
	switch (yych) {
	case 'F':	goto yy381;
	default:	goto yy99;
	}
yy57:
	yych = *++this->_cursor;
	switch (yych) {
	case 'N':	goto yy376;
	default:	goto yy99;
	}
yy58:
	yyaccept = 3;
	yych = *(this->_marker = ++this->_cursor);
	switch (yych) {
	case '"':	goto yy365;
	case '\'':	goto yy367;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	case 'O':	goto yy369;
	default:	goto yy51;
	}
yy59:
	yych = *++this->_cursor;
	switch (yych) {
	case 'L':	goto yy358;
	default:	goto yy99;
	}
yy60:
	yych = *++this->_cursor;
	switch (yych) {
	case 'U':	goto yy353;
	case 'W':	goto yy354;
	default:	goto yy99;
	}
yy61:
	yych = *++this->_cursor;
	switch (yych) {
	case 'H':	goto yy350;
	default:	goto yy99;
	}
yy62:
	yych = *++this->_cursor;
	switch (yych) {
	case 'B':	goto yy328;
	case 'C':	goto yy329;
	case 'I':	goto yy330;
	case 'L':	goto yy331;
	case 'Q':	goto yy332;
	case 'S':	goto yy333;
	default:	goto yy99;
	}
yy63:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy326;
	default:	goto yy99;
	}
yy64:
	++this->_cursor;
#line 65 "bt_lexer.re"
	{ TOKENIZE(BTT_O_SQUARE)  }
#line 536 "bt_lexer.cpp"
yy66:
	++this->_cursor;
#line 66 "bt_lexer.re"
	{ TOKENIZE(BTT_C_SQUARE)  }
#line 541 "bt_lexer.cpp"
yy68:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy324;
	default:	goto yy69;
	}
yy69:
#line 78 "bt_lexer.re"
	{ TOKENIZE(BTT_BIN_XOR) }
#line 551 "bt_lexer.cpp"
yy70:
	yych = *++this->_cursor;
	switch (yych) {
	case '_':	goto yy314;
	default:	goto yy99;
	}
yy71:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy301;
	case 'r':	goto yy302;
	case 'y':	goto yy303;
	default:	goto yy99;
	}
yy72:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy282;
	case 'h':	goto yy283;
	case 'o':	goto yy284;
	default:	goto yy99;
	}
yy73:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy268;
	case 'o':	goto yy269;
	default:	goto yy99;
	}
yy74:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy260;
	case 'n':	goto yy261;
	default:	goto yy99;
	}
yy75:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy247;
	case 'l':	goto yy248;
	case 'o':	goto yy249;
	default:	goto yy99;
	}
yy76:
	yych = *++this->_cursor;
	switch (yych) {
	case 'f':	goto yy241;
	default:	goto yy99;
	}
yy77:
	yych = *++this->_cursor;
	switch (yych) {
	case 'f':	goto yy234;
	case 'n':	goto yy236;
	default:	goto yy99;
	}
yy78:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy226;
	default:	goto yy99;
	}
yy79:
	yych = *++this->_cursor;
	switch (yych) {
	case 'u':	goto yy222;
	default:	goto yy99;
	}
yy80:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy216;
	default:	goto yy99;
	}
yy81:
	yych = *++this->_cursor;
	switch (yych) {
	case 'h':	goto yy184;
	case 'i':	goto yy185;
	case 't':	goto yy186;
	case 'w':	goto yy187;
	default:	goto yy99;
	}
yy82:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy167;
	case 'r':	goto yy168;
	case 'y':	goto yy169;
	default:	goto yy99;
	}
yy83:
	yych = *++this->_cursor;
	switch (yych) {
	case 'b':	goto yy123;
	case 'c':	goto yy124;
	case 'i':	goto yy125;
	case 'l':	goto yy126;
	case 'n':	goto yy127;
	case 'q':	goto yy128;
	case 's':	goto yy129;
	default:	goto yy99;
	}
yy84:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy119;
	default:	goto yy99;
	}
yy85:
	yych = *++this->_cursor;
	switch (yych) {
	case 'c':	goto yy100;
	case 'h':	goto yy101;
	case 's':	goto yy102;
	default:	goto yy99;
	}
yy86:
	++this->_cursor;
#line 67 "bt_lexer.re"
	{ TOKENIZE(BTT_O_CURLY)   }
#line 674 "bt_lexer.cpp"
yy88:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy94;
	case '|':	goto yy96;
	default:	goto yy89;
	}
yy89:
#line 77 "bt_lexer.re"
	{ TOKENIZE(BTT_BIN_OR)  }
#line 685 "bt_lexer.cpp"
yy90:
	++this->_cursor;
#line 68 "bt_lexer.re"
	{ TOKENIZE(BTT_C_CURLY)   }
#line 690 "bt_lexer.cpp"
yy92:
	++this->_cursor;
#line 79 "bt_lexer.re"
	{ TOKENIZE(BTT_BIN_NOT) }
#line 695 "bt_lexer.cpp"
yy94:
	++this->_cursor;
#line 97 "bt_lexer.re"
	{ TOKENIZE(BTT_OR_ASSIGN)     }
#line 700 "bt_lexer.cpp"
yy96:
	++this->_cursor;
#line 82 "bt_lexer.re"
	{ TOKENIZE(BTT_LOG_OR)  }
#line 705 "bt_lexer.cpp"
yy98:
	++this->_cursor;
	yych = *this->_cursor;
yy99:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy51;
	}
yy100:
	yych = *++this->_cursor;
	switch (yych) {
	case 'h':	goto yy113;
	default:	goto yy99;
	}
yy101:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy109;
	default:	goto yy99;
	}
yy102:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy103;
	default:	goto yy99;
	}
yy103:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy104;
	default:	goto yy99;
	}
yy104:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy105;
	default:	goto yy99;
	}
yy105:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy106;
	default:	goto yy99;
	}
yy106:
	yych = *++this->_cursor;
	switch (yych) {
	case 'g':	goto yy107;
	default:	goto yy99;
	}
yy107:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy108;
	}
yy108:
#line 116 "bt_lexer.re"
	{ TOKENIZE(BTT_WSTRING)  }
#line 889 "bt_lexer.cpp"
yy109:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy110;
	default:	goto yy99;
	}
yy110:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy111;
	default:	goto yy99;
	}
yy111:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy112;
	}
yy112:
#line 153 "bt_lexer.re"
	{ TOKENIZE(BTT_WHILE)    }
#line 973 "bt_lexer.cpp"
yy113:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy114;
	default:	goto yy99;
	}
yy114:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy115;
	default:	goto yy99;
	}
yy115:
	yych = *++this->_cursor;
	switch (yych) {
	case '_':	goto yy116;
	default:	goto yy99;
	}
yy116:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy117;
	default:	goto yy99;
	}
yy117:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy118;
	}
yy118:
#line 117 "bt_lexer.re"
	{ TOKENIZE(BTT_WCHAR)    }
#line 1069 "bt_lexer.cpp"
yy119:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy120;
	default:	goto yy99;
	}
yy120:
	yych = *++this->_cursor;
	switch (yych) {
	case 'd':	goto yy121;
	default:	goto yy99;
	}
yy121:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy122;
	}
yy122:
#line 113 "bt_lexer.re"
	{ TOKENIZE(BTT_VOID)     }
#line 1153 "bt_lexer.cpp"
yy123:
	yych = *++this->_cursor;
	switch (yych) {
	case 'y':	goto yy163;
	default:	goto yy99;
	}
yy124:
	yych = *++this->_cursor;
	switch (yych) {
	case 'h':	goto yy159;
	default:	goto yy99;
	}
yy125:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy154;
	default:	goto yy99;
	}
yy126:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy150;
	default:	goto yy99;
	}
yy127:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy139;
	case 's':	goto yy140;
	default:	goto yy99;
	}
yy128:
	yych = *++this->_cursor;
	switch (yych) {
	case 'u':	goto yy135;
	default:	goto yy99;
	}
yy129:
	yych = *++this->_cursor;
	switch (yych) {
	case 'h':	goto yy130;
	default:	goto yy99;
	}
yy130:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy131;
	default:	goto yy99;
	}
yy131:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy132;
	default:	goto yy99;
	}
yy132:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy133;
	default:	goto yy99;
	}
yy133:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy134;
	}
yy134:
#line 123 "bt_lexer.re"
	{ TOKENIZE(BTT_USHORT)   }
#line 1286 "bt_lexer.cpp"
yy135:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy136;
	default:	goto yy99;
	}
yy136:
	yych = *++this->_cursor;
	switch (yych) {
	case 'd':	goto yy137;
	default:	goto yy99;
	}
yy137:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy138;
	}
yy138:
#line 127 "bt_lexer.re"
	{ TOKENIZE(BTT_UINT64)   }
#line 1370 "bt_lexer.cpp"
yy139:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy147;
	default:	goto yy99;
	}
yy140:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy141;
	default:	goto yy99;
	}
yy141:
	yych = *++this->_cursor;
	switch (yych) {
	case 'g':	goto yy142;
	default:	goto yy99;
	}
yy142:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy143;
	default:	goto yy99;
	}
yy143:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy144;
	default:	goto yy99;
	}
yy144:
	yych = *++this->_cursor;
	switch (yych) {
	case 'd':	goto yy145;
	default:	goto yy99;
	}
yy145:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy146;
	}
yy146:
#line 157 "bt_lexer.re"
	{ TOKENIZE(BTT_UNSIGNED) }
#line 1478 "bt_lexer.cpp"
yy147:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy148;
	default:	goto yy99;
	}
yy148:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy149;
	}
yy149:
#line 145 "bt_lexer.re"
	{ TOKENIZE(BTT_UNION)    }
#line 1556 "bt_lexer.cpp"
yy150:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy151;
	default:	goto yy99;
	}
yy151:
	yych = *++this->_cursor;
	switch (yych) {
	case 'g':	goto yy152;
	default:	goto yy99;
	}
yy152:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy153;
	}
yy153:
#line 125 "bt_lexer.re"
	{ TOKENIZE(BTT_UINT32)   }
#line 1640 "bt_lexer.cpp"
yy154:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy155;
	default:	goto yy99;
	}
yy155:
	yych = *++this->_cursor;
	switch (yych) {
	case '0':
	case '2':
	case '4':
	case '5':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	case '1':	goto yy156;
	case '3':	goto yy157;
	case '6':	goto yy158;
	default:	goto yy153;
	}
yy156:
	yych = *++this->_cursor;
	switch (yych) {
	case '6':	goto yy133;
	default:	goto yy99;
	}
yy157:
	yych = *++this->_cursor;
	switch (yych) {
	case '2':	goto yy152;
	default:	goto yy99;
	}
yy158:
	yych = *++this->_cursor;
	switch (yych) {
	case '4':	goto yy137;
	default:	goto yy99;
	}
yy159:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy160;
	default:	goto yy99;
	}
yy160:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy161;
	default:	goto yy99;
	}
yy161:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy162;
	}
yy162:
#line 120 "bt_lexer.re"
	{ TOKENIZE(BTT_UCHAR)    }
#line 1816 "bt_lexer.cpp"
yy163:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy164;
	default:	goto yy99;
	}
yy164:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy165;
	default:	goto yy99;
	}
yy165:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy166;
	}
yy166:
#line 121 "bt_lexer.re"
	{ TOKENIZE(BTT_UBYTE)    }
#line 1900 "bt_lexer.cpp"
yy167:
	yych = *++this->_cursor;
	switch (yych) {
	case 'm':	goto yy179;
	default:	goto yy99;
	}
yy168:
	yych = *++this->_cursor;
	switch (yych) {
	case 'u':	goto yy176;
	default:	goto yy99;
	}
yy169:
	yych = *++this->_cursor;
	switch (yych) {
	case 'p':	goto yy170;
	default:	goto yy99;
	}
yy170:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy171;
	default:	goto yy99;
	}
yy171:
	yych = *++this->_cursor;
	switch (yych) {
	case 'd':	goto yy172;
	default:	goto yy99;
	}
yy172:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy173;
	default:	goto yy99;
	}
yy173:
	yych = *++this->_cursor;
	switch (yych) {
	case 'f':	goto yy174;
	default:	goto yy99;
	}
yy174:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy175;
	}
yy175:
#line 142 "bt_lexer.re"
	{ TOKENIZE(BTT_TYPEDEF)  }
#line 2014 "bt_lexer.cpp"
yy176:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy177;
	default:	goto yy99;
	}
yy177:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy178;
	}
yy178:
#line 158 "bt_lexer.re"
	{ TOKENIZE(BTT_TRUE)     }
#line 2092 "bt_lexer.cpp"
yy179:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy180;
	default:	goto yy99;
	}
yy180:
	yych = *++this->_cursor;
	switch (yych) {
	case '_':	goto yy181;
	default:	goto yy99;
	}
yy181:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy182;
	default:	goto yy99;
	}
yy182:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy183;
	}
yy183:
#line 131 "bt_lexer.re"
	{ TOKENIZE(BTT_TIME)     }
#line 2182 "bt_lexer.cpp"
yy184:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy212;
	default:	goto yy99;
	}
yy185:
	yych = *++this->_cursor;
	switch (yych) {
	case 'g':	goto yy203;
	case 'z':	goto yy202;
	default:	goto yy99;
	}
yy186:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy193;
	default:	goto yy99;
	}
yy187:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy188;
	default:	goto yy99;
	}
yy188:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy189;
	default:	goto yy99;
	}
yy189:
	yych = *++this->_cursor;
	switch (yych) {
	case 'c':	goto yy190;
	default:	goto yy99;
	}
yy190:
	yych = *++this->_cursor;
	switch (yych) {
	case 'h':	goto yy191;
	default:	goto yy99;
	}
yy191:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy192;
	}
yy192:
#line 152 "bt_lexer.re"
	{ TOKENIZE(BTT_SWITCH)   }
#line 2297 "bt_lexer.cpp"
yy193:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy194;
	case 'u':	goto yy195;
	default:	goto yy99;
	}
yy194:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy199;
	default:	goto yy99;
	}
yy195:
	yych = *++this->_cursor;
	switch (yych) {
	case 'c':	goto yy196;
	default:	goto yy99;
	}
yy196:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy197;
	default:	goto yy99;
	}
yy197:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy198;
	}
yy198:
#line 144 "bt_lexer.re"
	{ TOKENIZE(BTT_STRUCT)   }
#line 2394 "bt_lexer.cpp"
yy199:
	yych = *++this->_cursor;
	switch (yych) {
	case 'g':	goto yy200;
	default:	goto yy99;
	}
yy200:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy201;
	}
yy201:
#line 115 "bt_lexer.re"
	{ TOKENIZE(BTT_STRING)   }
#line 2472 "bt_lexer.cpp"
yy202:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy208;
	default:	goto yy99;
	}
yy203:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy204;
	default:	goto yy99;
	}
yy204:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy205;
	default:	goto yy99;
	}
yy205:
	yych = *++this->_cursor;
	switch (yych) {
	case 'd':	goto yy206;
	default:	goto yy99;
	}
yy206:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy207;
	}
yy207:
#line 156 "bt_lexer.re"
	{ TOKENIZE(BTT_SIGNED)   }
#line 2568 "bt_lexer.cpp"
yy208:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy209;
	default:	goto yy99;
	}
yy209:
	yych = *++this->_cursor;
	switch (yych) {
	case 'f':	goto yy210;
	default:	goto yy99;
	}
yy210:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy211;
	}
yy211:
#line 141 "bt_lexer.re"
	{ TOKENIZE(BTT_SIZEOF)   }
#line 2652 "bt_lexer.cpp"
yy212:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy213;
	default:	goto yy99;
	}
yy213:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy214;
	default:	goto yy99;
	}
yy214:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy215;
	}
yy215:
#line 122 "bt_lexer.re"
	{ TOKENIZE(BTT_SHORT)    }
#line 2736 "bt_lexer.cpp"
yy216:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy217;
	default:	goto yy99;
	}
yy217:
	yych = *++this->_cursor;
	switch (yych) {
	case 'u':	goto yy218;
	default:	goto yy99;
	}
yy218:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy219;
	default:	goto yy99;
	}
yy219:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy220;
	default:	goto yy99;
	}
yy220:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy221;
	}
yy221:
#line 146 "bt_lexer.re"
	{ TOKENIZE(BTT_RETURN)   }
#line 2832 "bt_lexer.cpp"
yy222:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy223;
	default:	goto yy99;
	}
yy223:
	yych = *++this->_cursor;
	switch (yych) {
	case 'd':	goto yy224;
	default:	goto yy99;
	}
yy224:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy225;
	}
yy225:
#line 126 "bt_lexer.re"
	{ TOKENIZE(BTT_INT64)    }
#line 2916 "bt_lexer.cpp"
yy226:
	yych = *++this->_cursor;
	switch (yych) {
	case 'c':	goto yy228;
	case 'n':	goto yy227;
	default:	goto yy99;
	}
yy227:
	yych = *++this->_cursor;
	switch (yych) {
	case 'g':	goto yy232;
	default:	goto yy99;
	}
yy228:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy229;
	default:	goto yy99;
	}
yy229:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy230;
	default:	goto yy99;
	}
yy230:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy231;
	}
yy231:
#line 138 "bt_lexer.re"
	{ TOKENIZE(BTT_LOCAL)    }
#line 3013 "bt_lexer.cpp"
yy232:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy233;
	}
yy233:
#line 124 "bt_lexer.re"
	{ TOKENIZE(BTT_INT32)    }
#line 3085 "bt_lexer.cpp"
yy234:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy235;
	}
yy235:
#line 150 "bt_lexer.re"
	{ TOKENIZE(BTT_IF)       }
#line 3157 "bt_lexer.cpp"
yy236:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy237;
	default:	goto yy99;
	}
yy237:
	yych = *++this->_cursor;
	switch (yych) {
	case '0':
	case '2':
	case '4':
	case '5':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	case '1':	goto yy238;
	case '3':	goto yy239;
	case '6':	goto yy240;
	default:	goto yy233;
	}
yy238:
	yych = *++this->_cursor;
	switch (yych) {
	case '6':	goto yy214;
	default:	goto yy99;
	}
yy239:
	yych = *++this->_cursor;
	switch (yych) {
	case '2':	goto yy232;
	default:	goto yy99;
	}
yy240:
	yych = *++this->_cursor;
	switch (yych) {
	case '4':	goto yy224;
	default:	goto yy99;
	}
yy241:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy242;
	default:	goto yy99;
	}
yy242:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy243;
	default:	goto yy99;
	}
yy243:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy244;
	default:	goto yy99;
	}
yy244:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy245;
	default:	goto yy99;
	}
yy245:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy246;
	}
yy246:
#line 128 "bt_lexer.re"
	{ TOKENIZE(BTT_HFLOAT)   }
#line 3345 "bt_lexer.cpp"
yy247:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy256;
	default:	goto yy99;
	}
yy248:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy252;
	default:	goto yy99;
	}
yy249:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy250;
	default:	goto yy99;
	}
yy250:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy251;
	}
yy251:
#line 149 "bt_lexer.re"
	{ TOKENIZE(BTT_FOR)      }
#line 3435 "bt_lexer.cpp"
yy252:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy253;
	default:	goto yy99;
	}
yy253:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy254;
	default:	goto yy99;
	}
yy254:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy255;
	}
yy255:
#line 129 "bt_lexer.re"
	{ TOKENIZE(BTT_FLOAT)    }
#line 3519 "bt_lexer.cpp"
yy256:
	yych = *++this->_cursor;
	switch (yych) {
	case 's':	goto yy257;
	default:	goto yy99;
	}
yy257:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy258;
	default:	goto yy99;
	}
yy258:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy259;
	}
yy259:
#line 159 "bt_lexer.re"
	{ TOKENIZE(BTT_FALSE)    }
#line 3603 "bt_lexer.cpp"
yy260:
	yych = *++this->_cursor;
	switch (yych) {
	case 's':	goto yy265;
	default:	goto yy99;
	}
yy261:
	yych = *++this->_cursor;
	switch (yych) {
	case 'u':	goto yy262;
	default:	goto yy99;
	}
yy262:
	yych = *++this->_cursor;
	switch (yych) {
	case 'm':	goto yy263;
	default:	goto yy99;
	}
yy263:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy264;
	}
yy264:
#line 143 "bt_lexer.re"
	{ TOKENIZE(BTT_ENUM)     }
#line 3693 "bt_lexer.cpp"
yy265:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy266;
	default:	goto yy99;
	}
yy266:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy267;
	}
yy267:
#line 151 "bt_lexer.re"
	{ TOKENIZE(BTT_ELSE)     }
#line 3771 "bt_lexer.cpp"
yy268:
	yych = *++this->_cursor;
	switch (yych) {
	case 'f':	goto yy276;
	default:	goto yy99;
	}
yy269:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	case 'u':	goto yy271;
	default:	goto yy270;
	}
yy270:
#line 154 "bt_lexer.re"
	{ TOKENIZE(BTT_DO)       }
#line 3849 "bt_lexer.cpp"
yy271:
	yych = *++this->_cursor;
	switch (yych) {
	case 'b':	goto yy272;
	default:	goto yy99;
	}
yy272:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy273;
	default:	goto yy99;
	}
yy273:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy274;
	default:	goto yy99;
	}
yy274:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy275;
	}
yy275:
#line 130 "bt_lexer.re"
	{ TOKENIZE(BTT_DOUBLE)   }
#line 3939 "bt_lexer.cpp"
yy276:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy277;
	default:	goto yy99;
	}
yy277:
	yych = *++this->_cursor;
	switch (yych) {
	case 'u':	goto yy278;
	default:	goto yy99;
	}
yy278:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy279;
	default:	goto yy99;
	}
yy279:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy280;
	default:	goto yy99;
	}
yy280:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy281;
	}
yy281:
#line 148 "bt_lexer.re"
	{ TOKENIZE(BTT_DEFAULT)  }
#line 4035 "bt_lexer.cpp"
yy282:
	yych = *++this->_cursor;
	switch (yych) {
	case 's':	goto yy298;
	default:	goto yy99;
	}
yy283:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy295;
	default:	goto yy99;
	}
yy284:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy285;
	default:	goto yy99;
	}
yy285:
	yych = *++this->_cursor;
	switch (yych) {
	case 's':	goto yy286;
	case 't':	goto yy287;
	default:	goto yy99;
	}
yy286:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy293;
	default:	goto yy99;
	}
yy287:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy288;
	default:	goto yy99;
	}
yy288:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy289;
	default:	goto yy99;
	}
yy289:
	yych = *++this->_cursor;
	switch (yych) {
	case 'u':	goto yy290;
	default:	goto yy99;
	}
yy290:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy291;
	default:	goto yy99;
	}
yy291:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy292;
	}
yy292:
#line 140 "bt_lexer.re"
	{ TOKENIZE(BTT_CONTINUE) }
#line 4162 "bt_lexer.cpp"
yy293:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy294;
	}
yy294:
#line 137 "bt_lexer.re"
	{ TOKENIZE(BTT_CONST)    }
#line 4234 "bt_lexer.cpp"
yy295:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy296;
	default:	goto yy99;
	}
yy296:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy297;
	}
yy297:
#line 118 "bt_lexer.re"
	{ TOKENIZE(BTT_CHAR)     }
#line 4312 "bt_lexer.cpp"
yy298:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy299;
	default:	goto yy99;
	}
yy299:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy300;
	}
yy300:
#line 147 "bt_lexer.re"
	{ TOKENIZE(BTT_CASE)     }
#line 4390 "bt_lexer.cpp"
yy301:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy311;
	default:	goto yy99;
	}
yy302:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy307;
	default:	goto yy99;
	}
yy303:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy304;
	default:	goto yy99;
	}
yy304:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy305;
	default:	goto yy99;
	}
yy305:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy306;
	}
yy306:
#line 119 "bt_lexer.re"
	{ TOKENIZE(BTT_BYTE)     }
#line 4486 "bt_lexer.cpp"
yy307:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy308;
	default:	goto yy99;
	}
yy308:
	yych = *++this->_cursor;
	switch (yych) {
	case 'k':	goto yy309;
	default:	goto yy99;
	}
yy309:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy310;
	}
yy310:
#line 139 "bt_lexer.re"
	{ TOKENIZE(BTT_BREAK)    }
#line 4570 "bt_lexer.cpp"
yy311:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy312;
	default:	goto yy99;
	}
yy312:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy313;
	}
yy313:
#line 114 "bt_lexer.re"
	{ TOKENIZE(BTT_BOOL)     }
#line 4648 "bt_lexer.cpp"
yy314:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy315;
	case 'u':	goto yy316;
	default:	goto yy99;
	}
yy315:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy321;
	default:	goto yy99;
	}
yy316:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy317;
	default:	goto yy99;
	}
yy317:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy318;
	default:	goto yy99;
	}
yy318:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy319;
	default:	goto yy99;
	}
yy319:
	yych = *++this->_cursor;
	switch (yych) {
	case '6':	goto yy320;
	default:	goto yy99;
	}
yy320:
	yych = *++this->_cursor;
	switch (yych) {
	case '4':	goto yy137;
	default:	goto yy99;
	}
yy321:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy322;
	default:	goto yy99;
	}
yy322:
	yych = *++this->_cursor;
	switch (yych) {
	case '6':	goto yy323;
	default:	goto yy99;
	}
yy323:
	yych = *++this->_cursor;
	switch (yych) {
	case '4':	goto yy224;
	default:	goto yy99;
	}
yy324:
	++this->_cursor;
#line 98 "bt_lexer.re"
	{ TOKENIZE(BTT_XOR_ASSIGN)    }
#line 4714 "bt_lexer.cpp"
yy326:
	yych = *++this->_cursor;
	switch (yych) {
	case 'R':	goto yy327;
	default:	goto yy99;
	}
yy327:
	yych = *++this->_cursor;
	switch (yych) {
	case 'D':	goto yy133;
	default:	goto yy99;
	}
yy328:
	yych = *++this->_cursor;
	switch (yych) {
	case 'Y':	goto yy348;
	default:	goto yy99;
	}
yy329:
	yych = *++this->_cursor;
	switch (yych) {
	case 'H':	goto yy346;
	default:	goto yy99;
	}
yy330:
	yych = *++this->_cursor;
	switch (yych) {
	case 'N':	goto yy341;
	default:	goto yy99;
	}
yy331:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy339;
	default:	goto yy99;
	}
yy332:
	yych = *++this->_cursor;
	switch (yych) {
	case 'U':	goto yy337;
	default:	goto yy99;
	}
yy333:
	yych = *++this->_cursor;
	switch (yych) {
	case 'H':	goto yy334;
	default:	goto yy99;
	}
yy334:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy335;
	default:	goto yy99;
	}
yy335:
	yych = *++this->_cursor;
	switch (yych) {
	case 'R':	goto yy336;
	default:	goto yy99;
	}
yy336:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy133;
	default:	goto yy99;
	}
yy337:
	yych = *++this->_cursor;
	switch (yych) {
	case 'A':	goto yy338;
	default:	goto yy99;
	}
yy338:
	yych = *++this->_cursor;
	switch (yych) {
	case 'D':	goto yy137;
	default:	goto yy99;
	}
yy339:
	yych = *++this->_cursor;
	switch (yych) {
	case 'N':	goto yy340;
	default:	goto yy99;
	}
yy340:
	yych = *++this->_cursor;
	switch (yych) {
	case 'G':	goto yy152;
	default:	goto yy99;
	}
yy341:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy342;
	default:	goto yy99;
	}
yy342:
	yych = *++this->_cursor;
	switch (yych) {
	case '0':
	case '2':
	case '4':
	case '5':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	case '1':	goto yy343;
	case '3':	goto yy344;
	case '6':	goto yy345;
	default:	goto yy153;
	}
yy343:
	yych = *++this->_cursor;
	switch (yych) {
	case '6':	goto yy133;
	default:	goto yy99;
	}
yy344:
	yych = *++this->_cursor;
	switch (yych) {
	case '2':	goto yy152;
	default:	goto yy99;
	}
yy345:
	yych = *++this->_cursor;
	switch (yych) {
	case '4':	goto yy137;
	default:	goto yy99;
	}
yy346:
	yych = *++this->_cursor;
	switch (yych) {
	case 'A':	goto yy347;
	default:	goto yy99;
	}
yy347:
	yych = *++this->_cursor;
	switch (yych) {
	case 'R':	goto yy161;
	default:	goto yy99;
	}
yy348:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy349;
	default:	goto yy99;
	}
yy349:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy165;
	default:	goto yy99;
	}
yy350:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy351;
	default:	goto yy99;
	}
yy351:
	yych = *++this->_cursor;
	switch (yych) {
	case 'R':	goto yy352;
	default:	goto yy99;
	}
yy352:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy214;
	default:	goto yy99;
	}
yy353:
	yych = *++this->_cursor;
	switch (yych) {
	case 'A':	goto yy357;
	default:	goto yy99;
	}
yy354:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy355;
	default:	goto yy99;
	}
yy355:
	yych = *++this->_cursor;
	switch (yych) {
	case 'R':	goto yy356;
	default:	goto yy99;
	}
yy356:
	yych = *++this->_cursor;
	switch (yych) {
	case 'D':	goto yy137;
	default:	goto yy99;
	}
yy357:
	yych = *++this->_cursor;
	switch (yych) {
	case 'D':	goto yy224;
	default:	goto yy99;
	}
yy358:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy359;
	default:	goto yy99;
	}
yy359:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy360;
	default:	goto yy99;
	}
yy360:
	yych = *++this->_cursor;
	switch (yych) {
	case 'I':	goto yy361;
	default:	goto yy99;
	}
yy361:
	yych = *++this->_cursor;
	switch (yych) {
	case 'M':	goto yy362;
	default:	goto yy99;
	}
yy362:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy363;
	default:	goto yy99;
	}
yy363:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy364;
	}
yy364:
#line 134 "bt_lexer.re"
	{ TOKENIZE(BTT_OLETIME)  }
#line 5070 "bt_lexer.cpp"
yy365:
	++this->_cursor;
	yych = *this->_cursor;
yy366:
	switch (yych) {
	case '"':	goto yy374;
	default:	goto yy365;
	}
yy367:
	yych = *++this->_cursor;
	switch (yych) {
	case '"':	goto yy368;
	default:	goto yy371;
	}
yy368:
	this->_cursor = this->_marker;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy33;
	case 2: 	goto yy35;
	default:	goto yy51;
	}
yy369:
	yych = *++this->_cursor;
	switch (yych) {
	case 'N':	goto yy370;
	default:	goto yy99;
	}
yy370:
	yych = *++this->_cursor;
	switch (yych) {
	case 'G':	goto yy232;
	default:	goto yy99;
	}
yy371:
	yych = *++this->_cursor;
	switch (yych) {
	case '\'':	goto yy372;
	default:	goto yy368;
	}
yy372:
	++this->_cursor;
#line 166 "bt_lexer.re"
	{ TOKENIZE_STRING_LITERAL(BTT_LITERAL_CHAR)   }
#line 5115 "bt_lexer.cpp"
yy374:
	++this->_cursor;
#line 167 "bt_lexer.re"
	{ TOKENIZE_STRING_LITERAL(BTT_LITERAL_STRING) }
#line 5120 "bt_lexer.cpp"
yy376:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy377;
	default:	goto yy99;
	}
yy377:
	yych = *++this->_cursor;
	switch (yych) {
	case '0':
	case '2':
	case '4':
	case '5':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	case '1':	goto yy378;
	case '3':	goto yy379;
	case '6':	goto yy380;
	default:	goto yy233;
	}
yy378:
	yych = *++this->_cursor;
	switch (yych) {
	case '6':	goto yy214;
	default:	goto yy99;
	}
yy379:
	yych = *++this->_cursor;
	switch (yych) {
	case '2':	goto yy232;
	default:	goto yy99;
	}
yy380:
	yych = *++this->_cursor;
	switch (yych) {
	case '4':	goto yy224;
	default:	goto yy99;
	}
yy381:
	yych = *++this->_cursor;
	switch (yych) {
	case 'L':	goto yy382;
	default:	goto yy99;
	}
yy382:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy383;
	default:	goto yy99;
	}
yy383:
	yych = *++this->_cursor;
	switch (yych) {
	case 'A':	goto yy384;
	default:	goto yy99;
	}
yy384:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy245;
	default:	goto yy99;
	}
yy385:
	yych = *++this->_cursor;
	switch (yych) {
	case 'L':	goto yy389;
	default:	goto yy99;
	}
yy386:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy387;
	default:	goto yy99;
	}
yy387:
	yych = *++this->_cursor;
	switch (yych) {
	case 'A':	goto yy388;
	default:	goto yy99;
	}
yy388:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy254;
	default:	goto yy99;
	}
yy389:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy390;
	default:	goto yy99;
	}
yy390:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy391;
	default:	goto yy99;
	}
yy391:
	yych = *++this->_cursor;
	switch (yych) {
	case 'I':	goto yy392;
	default:	goto yy99;
	}
yy392:
	yych = *++this->_cursor;
	switch (yych) {
	case 'M':	goto yy393;
	default:	goto yy99;
	}
yy393:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy394;
	default:	goto yy99;
	}
yy394:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy395;
	}
yy395:
#line 135 "bt_lexer.re"
	{ TOKENIZE(BTT_FILETIME) }
#line 5362 "bt_lexer.cpp"
yy396:
	yych = *++this->_cursor;
	switch (yych) {
	case 'S':	goto yy401;
	case 'U':	goto yy400;
	default:	goto yy99;
	}
yy397:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy398;
	default:	goto yy99;
	}
yy398:
	yych = *++this->_cursor;
	switch (yych) {
	case 'R':	goto yy399;
	default:	goto yy99;
	}
yy399:
	yych = *++this->_cursor;
	switch (yych) {
	case 'D':	goto yy152;
	default:	goto yy99;
	}
yy400:
	yych = *++this->_cursor;
	switch (yych) {
	case 'B':	goto yy412;
	default:	goto yy99;
	}
yy401:
	yych = *++this->_cursor;
	switch (yych) {
	case 'D':	goto yy402;
	case 'T':	goto yy403;
	default:	goto yy99;
	}
yy402:
	yych = *++this->_cursor;
	switch (yych) {
	case 'A':	goto yy408;
	default:	goto yy99;
	}
yy403:
	yych = *++this->_cursor;
	switch (yych) {
	case 'I':	goto yy404;
	default:	goto yy99;
	}
yy404:
	yych = *++this->_cursor;
	switch (yych) {
	case 'M':	goto yy405;
	default:	goto yy99;
	}
yy405:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy406;
	default:	goto yy99;
	}
yy406:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy407;
	}
yy407:
#line 133 "bt_lexer.re"
	{ TOKENIZE(BTT_DOSTIME)  }
#line 5496 "bt_lexer.cpp"
yy408:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy409;
	default:	goto yy99;
	}
yy409:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy410;
	default:	goto yy99;
	}
yy410:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy98;
	default:	goto yy411;
	}
yy411:
#line 132 "bt_lexer.re"
	{ TOKENIZE(BTT_DOSDATE)  }
#line 5580 "bt_lexer.cpp"
yy412:
	yych = *++this->_cursor;
	switch (yych) {
	case 'L':	goto yy413;
	default:	goto yy99;
	}
yy413:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy274;
	default:	goto yy99;
	}
yy414:
	yych = *++this->_cursor;
	switch (yych) {
	case 'A':	goto yy415;
	default:	goto yy99;
	}
yy415:
	yych = *++this->_cursor;
	switch (yych) {
	case 'R':	goto yy296;
	default:	goto yy99;
	}
yy416:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy417;
	default:	goto yy99;
	}
yy417:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy305;
	default:	goto yy99;
	}
yy418:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy422;
	default:	goto yy419;
	}
yy419:
#line 111 "bt_lexer.re"
	{ TOKENIZE(BTT_LSR) }
#line 5626 "bt_lexer.cpp"
yy420:
	++this->_cursor;
#line 90 "bt_lexer.re"
	{ TOKENIZE(BTT_GE) }
#line 5631 "bt_lexer.cpp"
yy422:
	++this->_cursor;
#line 100 "bt_lexer.re"
	{ TOKENIZE(BTT_RS_ASSIGN)     }
#line 5636 "bt_lexer.cpp"
yy424:
	++this->_cursor;
#line 85 "bt_lexer.re"
	{ TOKENIZE(BTT_EQ) }
#line 5641 "bt_lexer.cpp"
yy426:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy430;
	default:	goto yy427;
	}
yy427:
#line 110 "bt_lexer.re"
	{ TOKENIZE(BTT_LSL) }
#line 5651 "bt_lexer.cpp"
yy428:
	++this->_cursor;
#line 89 "bt_lexer.re"
	{ TOKENIZE(BTT_LE) }
#line 5656 "bt_lexer.cpp"
yy430:
	++this->_cursor;
#line 99 "bt_lexer.re"
	{ TOKENIZE(BTT_LS_ASSIGN)     }
#line 5661 "bt_lexer.cpp"
yy432:
	++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '.':	goto yy434;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy432;
	default:	goto yy37;
	}
yy434:
	++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy434;
	default:	goto yy436;
	}
yy436:
#line 162 "bt_lexer.re"
	{ TOKENIZE(BTT_LITERAL_REAL)                  }
#line 5698 "bt_lexer.cpp"
yy437:
	yych = *++this->_cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy442;
	default:	goto yy368;
	}
yy438:
	yyaccept = 2;
	this->_marker = ++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '.':	goto yy434;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy438;
	case '8':
	case '9':	goto yy440;
	default:	goto yy35;
	}
yy440:
	++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '.':	goto yy434;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy440;
	default:	goto yy368;
	}
yy442:
	++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy442;
	default:	goto yy444;
	}
yy444:
#line 165 "bt_lexer.re"
	{ TOKENIZE(BTT_LITERAL_HEX)                   }
#line 5792 "bt_lexer.cpp"
yy445:
	++this->_cursor;
#line 95 "bt_lexer.re"
	{ TOKENIZE(BTT_DIV_ASSIGN)    }
#line 5797 "bt_lexer.cpp"
yy447:
	++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '*':	goto yy452;
	default:	goto yy447;
	}
yy449:
	++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '\n':	goto yy451;
	default:	goto yy449;
	}
yy451:
	yych = *++this->_cursor;
	goto yy9;
yy452:
	++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '/':	goto yy453;
	default:	goto yy447;
	}
yy453:
	yych = *++this->_cursor;
	goto yy7;
yy454:
	++this->_cursor;
#line 103 "bt_lexer.re"
	{ TOKENIZE(BTT_DEC) }
#line 5829 "bt_lexer.cpp"
yy456:
	++this->_cursor;
#line 93 "bt_lexer.re"
	{ TOKENIZE(BTT_SUB_ASSIGN)    }
#line 5834 "bt_lexer.cpp"
yy458:
	++this->_cursor;
#line 102 "bt_lexer.re"
	{ TOKENIZE(BTT_INC) }
#line 5839 "bt_lexer.cpp"
yy460:
	++this->_cursor;
#line 92 "bt_lexer.re"
	{ TOKENIZE(BTT_ADD_ASSIGN)    }
#line 5844 "bt_lexer.cpp"
yy462:
	++this->_cursor;
#line 94 "bt_lexer.re"
	{ TOKENIZE(BTT_MUL_ASSIGN)    }
#line 5849 "bt_lexer.cpp"
yy464:
	++this->_cursor;
#line 96 "bt_lexer.re"
	{ TOKENIZE(BTT_AND_ASSIGN)    }
#line 5854 "bt_lexer.cpp"
yy466:
	++this->_cursor;
#line 81 "bt_lexer.re"
	{ TOKENIZE(BTT_LOG_AND) }
#line 5859 "bt_lexer.cpp"
yy468:
	++this->_cursor;
#line 86 "bt_lexer.re"
	{ TOKENIZE(BTT_NE) }
#line 5864 "bt_lexer.cpp"
yy470:
	++this->_cursor;
	yych = *this->_cursor;
yy471:
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':
	case '\\':	goto yy470;
	default:	goto yy7;
	}
}
#line 170 "bt_lexer.re"

    }

    return tokens;
}
 
