/* Generated by re2c 0.14.3 on Fri Mar 17 17:56:15 2017 */
#line 1 "bt_lexer.re"
#include "bt_lexer.h"
#include "bt_parser.h"

#define TOKEN_STRING string(start, this->_cursor - start)
#define TOKEN_STRING_LITERAL string(start + 1, this->_cursor - (start + 2))

#define UNKNOWN_TOKEN cout << "Unknown token: " << TOKEN_STRING << endl; \
                              continue;

#define TOKENIZE(token_type) token.value = TOKEN_STRING; \
                             token.type = token_type;    \
                             token.line = currentline;   \
                             tokens.push_back(token);    \
                             continue;

#define TOKENIZE_STRING_LITERAL(token_type) token.value = TOKEN_STRING_LITERAL; \
                                            token.type = token_type;    \
                                            token.line = currentline;   \
                                            tokens.push_back(token);    \
                                            continue;

BTLexer::BTLexer(const char* s): _cursor(s), _start(NULL), _marker(NULL)
{
}

string BTLexer::getString(const char* start, const char* end) const
{
    return string(start, end - start);
}

list<BTLexer::Token> BTLexer::lex()
{
    list<BTLexer::Token> tokens;
    unsigned int currentline = 0;

    for(; ;)
    {
        Token token;
        const char* start = this->_cursor;

        
#line 45 "bt_lexer.cpp"
{
	char yych;
	unsigned int yyaccept = 0;

	yych = *this->_cursor;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\r':
	case ' ':	goto yy6;
	case '\n':	goto yy8;
	case '!':	goto yy10;
	case '"':	goto yy12;
	case '%':	goto yy13;
	case '&':	goto yy15;
	case '(':	goto yy17;
	case ')':	goto yy19;
	case '*':	goto yy21;
	case '+':	goto yy23;
	case ',':	goto yy25;
	case '-':	goto yy27;
	case '.':	goto yy29;
	case '/':	goto yy31;
	case '0':	goto yy33;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy35;
	case ':':	goto yy37;
	case ';':	goto yy39;
	case '<':	goto yy41;
	case '=':	goto yy43;
	case '>':	goto yy45;
	case '?':	goto yy47;
	case 'A':
	case 'E':
	case 'G':
	case 'J':
	case 'K':
	case 'M':
	case 'N':
	case 'P':
	case 'R':
	case 'T':
	case 'V':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'g':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'x':
	case 'y':
	case 'z':	goto yy49;
	case 'B':	goto yy51;
	case 'C':	goto yy52;
	case 'D':	goto yy53;
	case 'F':	goto yy54;
	case 'H':	goto yy55;
	case 'I':	goto yy56;
	case 'L':	goto yy57;
	case 'O':	goto yy58;
	case 'Q':	goto yy59;
	case 'S':	goto yy60;
	case 'U':	goto yy61;
	case 'W':	goto yy62;
	case '[':	goto yy63;
	case ']':	goto yy65;
	case '^':	goto yy67;
	case '_':	goto yy69;
	case 'b':	goto yy70;
	case 'c':	goto yy71;
	case 'd':	goto yy72;
	case 'e':	goto yy73;
	case 'f':	goto yy74;
	case 'h':	goto yy75;
	case 'i':	goto yy76;
	case 'l':	goto yy77;
	case 'q':	goto yy78;
	case 'r':	goto yy79;
	case 's':	goto yy80;
	case 't':	goto yy81;
	case 'u':	goto yy82;
	case 'v':	goto yy83;
	case 'w':	goto yy84;
	case '{':	goto yy85;
	case '|':	goto yy87;
	case '}':	goto yy89;
	case '~':	goto yy91;
	default:	goto yy4;
	}
yy2:
	++this->_cursor;
#line 58 "bt_lexer.re"
	{ break; }
#line 151 "bt_lexer.cpp"
yy4:
	++this->_cursor;
yy5:
#line 167 "bt_lexer.re"
	{ UNKNOWN_TOKEN }
#line 157 "bt_lexer.cpp"
yy6:
	++this->_cursor;
	yych = *this->_cursor;
	goto yy466;
yy7:
#line 60 "bt_lexer.re"
	{ continue; }
#line 165 "bt_lexer.cpp"
yy8:
	++this->_cursor;
yy9:
#line 59 "bt_lexer.re"
	{ currentline++; continue; }
#line 171 "bt_lexer.cpp"
yy10:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy463;
	default:	goto yy11;
	}
yy11:
#line 82 "bt_lexer.re"
	{ TOKENIZE(BTT_LOG_NOT) }
#line 181 "bt_lexer.cpp"
yy12:
	yyaccept = 0;
	yych = *(this->_marker = ++this->_cursor);
	goto yy365;
yy13:
	++this->_cursor;
#line 108 "bt_lexer.re"
	{ TOKENIZE(BTT_MOD) }
#line 190 "bt_lexer.cpp"
yy15:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '&':	goto yy461;
	case '=':	goto yy459;
	default:	goto yy16;
	}
yy16:
#line 75 "bt_lexer.re"
	{ TOKENIZE(BTT_BIN_AND) }
#line 201 "bt_lexer.cpp"
yy17:
	++this->_cursor;
#line 62 "bt_lexer.re"
	{ TOKENIZE(BTT_O_ROUND)   }
#line 206 "bt_lexer.cpp"
yy19:
	++this->_cursor;
#line 63 "bt_lexer.re"
	{ TOKENIZE(BTT_C_ROUND)   }
#line 211 "bt_lexer.cpp"
yy21:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy457;
	default:	goto yy22;
	}
yy22:
#line 106 "bt_lexer.re"
	{ TOKENIZE(BTT_MUL) }
#line 221 "bt_lexer.cpp"
yy23:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '+':	goto yy453;
	case '=':	goto yy455;
	default:	goto yy24;
	}
yy24:
#line 104 "bt_lexer.re"
	{ TOKENIZE(BTT_ADD) }
#line 232 "bt_lexer.cpp"
yy25:
	++this->_cursor;
#line 68 "bt_lexer.re"
	{ TOKENIZE(BTT_COMMA)     }
#line 237 "bt_lexer.cpp"
yy27:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '-':	goto yy449;
	case '=':	goto yy451;
	default:	goto yy28;
	}
yy28:
#line 105 "bt_lexer.re"
	{ TOKENIZE(BTT_SUB) }
#line 248 "bt_lexer.cpp"
yy29:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy428;
	default:	goto yy30;
	}
yy30:
#line 69 "bt_lexer.re"
	{ TOKENIZE(BTT_DOT)       }
#line 267 "bt_lexer.cpp"
yy31:
	yyaccept = 1;
	yych = *(this->_marker = ++this->_cursor);
	switch (yych) {
	case '*':	goto yy442;
	case '/':	goto yy444;
	case '=':	goto yy440;
	default:	goto yy32;
	}
yy32:
#line 107 "bt_lexer.re"
	{ TOKENIZE(BTT_DIV) }
#line 280 "bt_lexer.cpp"
yy33:
	yyaccept = 2;
	yych = *(this->_marker = ++this->_cursor);
	switch (yych) {
	case '.':	goto yy428;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy433;
	case '8':
	case '9':	goto yy435;
	case 'x':	goto yy431;
	default:	goto yy34;
	}
yy34:
#line 162 "bt_lexer.re"
	{ TOKENIZE(BTT_LITERAL_OCT)                   }
#line 302 "bt_lexer.cpp"
yy35:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '.':	goto yy428;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy426;
	default:	goto yy36;
	}
yy36:
#line 163 "bt_lexer.re"
	{ TOKENIZE(BTT_LITERAL_DEC)                   }
#line 322 "bt_lexer.cpp"
yy37:
	++this->_cursor;
#line 71 "bt_lexer.re"
	{ TOKENIZE(BTT_COLON)     }
#line 327 "bt_lexer.cpp"
yy39:
	++this->_cursor;
#line 70 "bt_lexer.re"
	{ TOKENIZE(BTT_SEMICOLON) }
#line 332 "bt_lexer.cpp"
yy41:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '<':	goto yy420;
	case '=':	goto yy422;
	default:	goto yy42;
	}
yy42:
#line 86 "bt_lexer.re"
	{ TOKENIZE(BTT_LT) }
#line 343 "bt_lexer.cpp"
yy43:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy418;
	default:	goto yy44;
	}
yy44:
#line 72 "bt_lexer.re"
	{ TOKENIZE(BTT_ASSIGN)    }
#line 353 "bt_lexer.cpp"
yy45:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy414;
	case '>':	goto yy412;
	default:	goto yy46;
	}
yy46:
#line 87 "bt_lexer.re"
	{ TOKENIZE(BTT_GT) }
#line 364 "bt_lexer.cpp"
yy47:
	++this->_cursor;
#line 73 "bt_lexer.re"
	{ TOKENIZE(BTT_QUESTION)  }
#line 369 "bt_lexer.cpp"
yy49:
	++this->_cursor;
	yych = *this->_cursor;
	goto yy98;
yy50:
#line 160 "bt_lexer.re"
	{ TOKENIZE(BTT_IDENTIFIER)                    }
#line 377 "bt_lexer.cpp"
yy51:
	yych = *++this->_cursor;
	switch (yych) {
	case 'Y':	goto yy410;
	default:	goto yy98;
	}
yy52:
	yych = *++this->_cursor;
	switch (yych) {
	case 'H':	goto yy408;
	default:	goto yy98;
	}
yy53:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy390;
	case 'W':	goto yy391;
	default:	goto yy98;
	}
yy54:
	yych = *++this->_cursor;
	switch (yych) {
	case 'I':	goto yy379;
	case 'L':	goto yy380;
	default:	goto yy98;
	}
yy55:
	yych = *++this->_cursor;
	switch (yych) {
	case 'F':	goto yy375;
	default:	goto yy98;
	}
yy56:
	yych = *++this->_cursor;
	switch (yych) {
	case 'N':	goto yy370;
	default:	goto yy98;
	}
yy57:
	yyaccept = 3;
	yych = *(this->_marker = ++this->_cursor);
	switch (yych) {
	case '"':	goto yy364;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	case 'O':	goto yy366;
	default:	goto yy50;
	}
yy58:
	yych = *++this->_cursor;
	switch (yych) {
	case 'L':	goto yy357;
	default:	goto yy98;
	}
yy59:
	yych = *++this->_cursor;
	switch (yych) {
	case 'U':	goto yy352;
	case 'W':	goto yy353;
	default:	goto yy98;
	}
yy60:
	yych = *++this->_cursor;
	switch (yych) {
	case 'H':	goto yy349;
	default:	goto yy98;
	}
yy61:
	yych = *++this->_cursor;
	switch (yych) {
	case 'B':	goto yy327;
	case 'C':	goto yy328;
	case 'I':	goto yy329;
	case 'L':	goto yy330;
	case 'Q':	goto yy331;
	case 'S':	goto yy332;
	default:	goto yy98;
	}
yy62:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy325;
	default:	goto yy98;
	}
yy63:
	++this->_cursor;
#line 64 "bt_lexer.re"
	{ TOKENIZE(BTT_O_SQUARE)  }
#line 526 "bt_lexer.cpp"
yy65:
	++this->_cursor;
#line 65 "bt_lexer.re"
	{ TOKENIZE(BTT_C_SQUARE)  }
#line 531 "bt_lexer.cpp"
yy67:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy323;
	default:	goto yy68;
	}
yy68:
#line 77 "bt_lexer.re"
	{ TOKENIZE(BTT_BIN_XOR) }
#line 541 "bt_lexer.cpp"
yy69:
	yych = *++this->_cursor;
	switch (yych) {
	case '_':	goto yy313;
	default:	goto yy98;
	}
yy70:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy300;
	case 'r':	goto yy301;
	case 'y':	goto yy302;
	default:	goto yy98;
	}
yy71:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy281;
	case 'h':	goto yy282;
	case 'o':	goto yy283;
	default:	goto yy98;
	}
yy72:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy267;
	case 'o':	goto yy268;
	default:	goto yy98;
	}
yy73:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy259;
	case 'n':	goto yy260;
	default:	goto yy98;
	}
yy74:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy246;
	case 'l':	goto yy247;
	case 'o':	goto yy248;
	default:	goto yy98;
	}
yy75:
	yych = *++this->_cursor;
	switch (yych) {
	case 'f':	goto yy240;
	default:	goto yy98;
	}
yy76:
	yych = *++this->_cursor;
	switch (yych) {
	case 'f':	goto yy233;
	case 'n':	goto yy235;
	default:	goto yy98;
	}
yy77:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy225;
	default:	goto yy98;
	}
yy78:
	yych = *++this->_cursor;
	switch (yych) {
	case 'u':	goto yy221;
	default:	goto yy98;
	}
yy79:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy215;
	default:	goto yy98;
	}
yy80:
	yych = *++this->_cursor;
	switch (yych) {
	case 'h':	goto yy183;
	case 'i':	goto yy184;
	case 't':	goto yy185;
	case 'w':	goto yy186;
	default:	goto yy98;
	}
yy81:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy166;
	case 'r':	goto yy167;
	case 'y':	goto yy168;
	default:	goto yy98;
	}
yy82:
	yych = *++this->_cursor;
	switch (yych) {
	case 'b':	goto yy122;
	case 'c':	goto yy123;
	case 'i':	goto yy124;
	case 'l':	goto yy125;
	case 'n':	goto yy126;
	case 'q':	goto yy127;
	case 's':	goto yy128;
	default:	goto yy98;
	}
yy83:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy118;
	default:	goto yy98;
	}
yy84:
	yych = *++this->_cursor;
	switch (yych) {
	case 'c':	goto yy99;
	case 'h':	goto yy100;
	case 's':	goto yy101;
	default:	goto yy98;
	}
yy85:
	++this->_cursor;
#line 66 "bt_lexer.re"
	{ TOKENIZE(BTT_O_CURLY)   }
#line 664 "bt_lexer.cpp"
yy87:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy93;
	case '|':	goto yy95;
	default:	goto yy88;
	}
yy88:
#line 76 "bt_lexer.re"
	{ TOKENIZE(BTT_BIN_OR)  }
#line 675 "bt_lexer.cpp"
yy89:
	++this->_cursor;
#line 67 "bt_lexer.re"
	{ TOKENIZE(BTT_C_CURLY)   }
#line 680 "bt_lexer.cpp"
yy91:
	++this->_cursor;
#line 78 "bt_lexer.re"
	{ TOKENIZE(BTT_BIN_NOT) }
#line 685 "bt_lexer.cpp"
yy93:
	++this->_cursor;
#line 96 "bt_lexer.re"
	{ TOKENIZE(BTT_OR_ASSIGN)     }
#line 690 "bt_lexer.cpp"
yy95:
	++this->_cursor;
#line 81 "bt_lexer.re"
	{ TOKENIZE(BTT_LOG_OR)  }
#line 695 "bt_lexer.cpp"
yy97:
	++this->_cursor;
	yych = *this->_cursor;
yy98:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy50;
	}
yy99:
	yych = *++this->_cursor;
	switch (yych) {
	case 'h':	goto yy112;
	default:	goto yy98;
	}
yy100:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy108;
	default:	goto yy98;
	}
yy101:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy102;
	default:	goto yy98;
	}
yy102:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy103;
	default:	goto yy98;
	}
yy103:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy104;
	default:	goto yy98;
	}
yy104:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy105;
	default:	goto yy98;
	}
yy105:
	yych = *++this->_cursor;
	switch (yych) {
	case 'g':	goto yy106;
	default:	goto yy98;
	}
yy106:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy107;
	}
yy107:
#line 115 "bt_lexer.re"
	{ TOKENIZE(BTT_WSTRING)  }
#line 879 "bt_lexer.cpp"
yy108:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy109;
	default:	goto yy98;
	}
yy109:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy110;
	default:	goto yy98;
	}
yy110:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy111;
	}
yy111:
#line 152 "bt_lexer.re"
	{ TOKENIZE(BTT_WHILE)    }
#line 963 "bt_lexer.cpp"
yy112:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy113;
	default:	goto yy98;
	}
yy113:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy114;
	default:	goto yy98;
	}
yy114:
	yych = *++this->_cursor;
	switch (yych) {
	case '_':	goto yy115;
	default:	goto yy98;
	}
yy115:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy116;
	default:	goto yy98;
	}
yy116:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy117;
	}
yy117:
#line 116 "bt_lexer.re"
	{ TOKENIZE(BTT_WCHAR)    }
#line 1059 "bt_lexer.cpp"
yy118:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy119;
	default:	goto yy98;
	}
yy119:
	yych = *++this->_cursor;
	switch (yych) {
	case 'd':	goto yy120;
	default:	goto yy98;
	}
yy120:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy121;
	}
yy121:
#line 112 "bt_lexer.re"
	{ TOKENIZE(BTT_VOID)     }
#line 1143 "bt_lexer.cpp"
yy122:
	yych = *++this->_cursor;
	switch (yych) {
	case 'y':	goto yy162;
	default:	goto yy98;
	}
yy123:
	yych = *++this->_cursor;
	switch (yych) {
	case 'h':	goto yy158;
	default:	goto yy98;
	}
yy124:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy153;
	default:	goto yy98;
	}
yy125:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy149;
	default:	goto yy98;
	}
yy126:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy138;
	case 's':	goto yy139;
	default:	goto yy98;
	}
yy127:
	yych = *++this->_cursor;
	switch (yych) {
	case 'u':	goto yy134;
	default:	goto yy98;
	}
yy128:
	yych = *++this->_cursor;
	switch (yych) {
	case 'h':	goto yy129;
	default:	goto yy98;
	}
yy129:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy130;
	default:	goto yy98;
	}
yy130:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy131;
	default:	goto yy98;
	}
yy131:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy132;
	default:	goto yy98;
	}
yy132:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy133;
	}
yy133:
#line 122 "bt_lexer.re"
	{ TOKENIZE(BTT_USHORT)   }
#line 1276 "bt_lexer.cpp"
yy134:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy135;
	default:	goto yy98;
	}
yy135:
	yych = *++this->_cursor;
	switch (yych) {
	case 'd':	goto yy136;
	default:	goto yy98;
	}
yy136:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy137;
	}
yy137:
#line 126 "bt_lexer.re"
	{ TOKENIZE(BTT_UINT64)   }
#line 1360 "bt_lexer.cpp"
yy138:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy146;
	default:	goto yy98;
	}
yy139:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy140;
	default:	goto yy98;
	}
yy140:
	yych = *++this->_cursor;
	switch (yych) {
	case 'g':	goto yy141;
	default:	goto yy98;
	}
yy141:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy142;
	default:	goto yy98;
	}
yy142:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy143;
	default:	goto yy98;
	}
yy143:
	yych = *++this->_cursor;
	switch (yych) {
	case 'd':	goto yy144;
	default:	goto yy98;
	}
yy144:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy145;
	}
yy145:
#line 156 "bt_lexer.re"
	{ TOKENIZE(BTT_UNSIGNED) }
#line 1468 "bt_lexer.cpp"
yy146:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy147;
	default:	goto yy98;
	}
yy147:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy148;
	}
yy148:
#line 144 "bt_lexer.re"
	{ TOKENIZE(BTT_UNION)    }
#line 1546 "bt_lexer.cpp"
yy149:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy150;
	default:	goto yy98;
	}
yy150:
	yych = *++this->_cursor;
	switch (yych) {
	case 'g':	goto yy151;
	default:	goto yy98;
	}
yy151:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy152;
	}
yy152:
#line 124 "bt_lexer.re"
	{ TOKENIZE(BTT_UINT32)   }
#line 1630 "bt_lexer.cpp"
yy153:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy154;
	default:	goto yy98;
	}
yy154:
	yych = *++this->_cursor;
	switch (yych) {
	case '0':
	case '2':
	case '4':
	case '5':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	case '1':	goto yy155;
	case '3':	goto yy156;
	case '6':	goto yy157;
	default:	goto yy152;
	}
yy155:
	yych = *++this->_cursor;
	switch (yych) {
	case '6':	goto yy132;
	default:	goto yy98;
	}
yy156:
	yych = *++this->_cursor;
	switch (yych) {
	case '2':	goto yy151;
	default:	goto yy98;
	}
yy157:
	yych = *++this->_cursor;
	switch (yych) {
	case '4':	goto yy136;
	default:	goto yy98;
	}
yy158:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy159;
	default:	goto yy98;
	}
yy159:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy160;
	default:	goto yy98;
	}
yy160:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy161;
	}
yy161:
#line 119 "bt_lexer.re"
	{ TOKENIZE(BTT_UCHAR)    }
#line 1806 "bt_lexer.cpp"
yy162:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy163;
	default:	goto yy98;
	}
yy163:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy164;
	default:	goto yy98;
	}
yy164:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy165;
	}
yy165:
#line 120 "bt_lexer.re"
	{ TOKENIZE(BTT_UBYTE)    }
#line 1890 "bt_lexer.cpp"
yy166:
	yych = *++this->_cursor;
	switch (yych) {
	case 'm':	goto yy178;
	default:	goto yy98;
	}
yy167:
	yych = *++this->_cursor;
	switch (yych) {
	case 'u':	goto yy175;
	default:	goto yy98;
	}
yy168:
	yych = *++this->_cursor;
	switch (yych) {
	case 'p':	goto yy169;
	default:	goto yy98;
	}
yy169:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy170;
	default:	goto yy98;
	}
yy170:
	yych = *++this->_cursor;
	switch (yych) {
	case 'd':	goto yy171;
	default:	goto yy98;
	}
yy171:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy172;
	default:	goto yy98;
	}
yy172:
	yych = *++this->_cursor;
	switch (yych) {
	case 'f':	goto yy173;
	default:	goto yy98;
	}
yy173:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy174;
	}
yy174:
#line 141 "bt_lexer.re"
	{ TOKENIZE(BTT_TYPEDEF)  }
#line 2004 "bt_lexer.cpp"
yy175:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy176;
	default:	goto yy98;
	}
yy176:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy177;
	}
yy177:
#line 157 "bt_lexer.re"
	{ TOKENIZE(BTT_TRUE)     }
#line 2082 "bt_lexer.cpp"
yy178:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy179;
	default:	goto yy98;
	}
yy179:
	yych = *++this->_cursor;
	switch (yych) {
	case '_':	goto yy180;
	default:	goto yy98;
	}
yy180:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy181;
	default:	goto yy98;
	}
yy181:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy182;
	}
yy182:
#line 130 "bt_lexer.re"
	{ TOKENIZE(BTT_TIME)     }
#line 2172 "bt_lexer.cpp"
yy183:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy211;
	default:	goto yy98;
	}
yy184:
	yych = *++this->_cursor;
	switch (yych) {
	case 'g':	goto yy202;
	case 'z':	goto yy201;
	default:	goto yy98;
	}
yy185:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy192;
	default:	goto yy98;
	}
yy186:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy187;
	default:	goto yy98;
	}
yy187:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy188;
	default:	goto yy98;
	}
yy188:
	yych = *++this->_cursor;
	switch (yych) {
	case 'c':	goto yy189;
	default:	goto yy98;
	}
yy189:
	yych = *++this->_cursor;
	switch (yych) {
	case 'h':	goto yy190;
	default:	goto yy98;
	}
yy190:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy191;
	}
yy191:
#line 151 "bt_lexer.re"
	{ TOKENIZE(BTT_SWITCH)   }
#line 2287 "bt_lexer.cpp"
yy192:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy193;
	case 'u':	goto yy194;
	default:	goto yy98;
	}
yy193:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy198;
	default:	goto yy98;
	}
yy194:
	yych = *++this->_cursor;
	switch (yych) {
	case 'c':	goto yy195;
	default:	goto yy98;
	}
yy195:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy196;
	default:	goto yy98;
	}
yy196:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy197;
	}
yy197:
#line 143 "bt_lexer.re"
	{ TOKENIZE(BTT_STRUCT)   }
#line 2384 "bt_lexer.cpp"
yy198:
	yych = *++this->_cursor;
	switch (yych) {
	case 'g':	goto yy199;
	default:	goto yy98;
	}
yy199:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy200;
	}
yy200:
#line 114 "bt_lexer.re"
	{ TOKENIZE(BTT_STRING)   }
#line 2462 "bt_lexer.cpp"
yy201:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy207;
	default:	goto yy98;
	}
yy202:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy203;
	default:	goto yy98;
	}
yy203:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy204;
	default:	goto yy98;
	}
yy204:
	yych = *++this->_cursor;
	switch (yych) {
	case 'd':	goto yy205;
	default:	goto yy98;
	}
yy205:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy206;
	}
yy206:
#line 155 "bt_lexer.re"
	{ TOKENIZE(BTT_SIGNED)   }
#line 2558 "bt_lexer.cpp"
yy207:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy208;
	default:	goto yy98;
	}
yy208:
	yych = *++this->_cursor;
	switch (yych) {
	case 'f':	goto yy209;
	default:	goto yy98;
	}
yy209:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy210;
	}
yy210:
#line 140 "bt_lexer.re"
	{ TOKENIZE(BTT_SIZEOF)   }
#line 2642 "bt_lexer.cpp"
yy211:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy212;
	default:	goto yy98;
	}
yy212:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy213;
	default:	goto yy98;
	}
yy213:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy214;
	}
yy214:
#line 121 "bt_lexer.re"
	{ TOKENIZE(BTT_SHORT)    }
#line 2726 "bt_lexer.cpp"
yy215:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy216;
	default:	goto yy98;
	}
yy216:
	yych = *++this->_cursor;
	switch (yych) {
	case 'u':	goto yy217;
	default:	goto yy98;
	}
yy217:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy218;
	default:	goto yy98;
	}
yy218:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy219;
	default:	goto yy98;
	}
yy219:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy220;
	}
yy220:
#line 145 "bt_lexer.re"
	{ TOKENIZE(BTT_RETURN)   }
#line 2822 "bt_lexer.cpp"
yy221:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy222;
	default:	goto yy98;
	}
yy222:
	yych = *++this->_cursor;
	switch (yych) {
	case 'd':	goto yy223;
	default:	goto yy98;
	}
yy223:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy224;
	}
yy224:
#line 125 "bt_lexer.re"
	{ TOKENIZE(BTT_INT64)    }
#line 2906 "bt_lexer.cpp"
yy225:
	yych = *++this->_cursor;
	switch (yych) {
	case 'c':	goto yy227;
	case 'n':	goto yy226;
	default:	goto yy98;
	}
yy226:
	yych = *++this->_cursor;
	switch (yych) {
	case 'g':	goto yy231;
	default:	goto yy98;
	}
yy227:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy228;
	default:	goto yy98;
	}
yy228:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy229;
	default:	goto yy98;
	}
yy229:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy230;
	}
yy230:
#line 137 "bt_lexer.re"
	{ TOKENIZE(BTT_LOCAL)    }
#line 3003 "bt_lexer.cpp"
yy231:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy232;
	}
yy232:
#line 123 "bt_lexer.re"
	{ TOKENIZE(BTT_INT32)    }
#line 3075 "bt_lexer.cpp"
yy233:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy234;
	}
yy234:
#line 149 "bt_lexer.re"
	{ TOKENIZE(BTT_IF)       }
#line 3147 "bt_lexer.cpp"
yy235:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy236;
	default:	goto yy98;
	}
yy236:
	yych = *++this->_cursor;
	switch (yych) {
	case '0':
	case '2':
	case '4':
	case '5':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	case '1':	goto yy237;
	case '3':	goto yy238;
	case '6':	goto yy239;
	default:	goto yy232;
	}
yy237:
	yych = *++this->_cursor;
	switch (yych) {
	case '6':	goto yy213;
	default:	goto yy98;
	}
yy238:
	yych = *++this->_cursor;
	switch (yych) {
	case '2':	goto yy231;
	default:	goto yy98;
	}
yy239:
	yych = *++this->_cursor;
	switch (yych) {
	case '4':	goto yy223;
	default:	goto yy98;
	}
yy240:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy241;
	default:	goto yy98;
	}
yy241:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy242;
	default:	goto yy98;
	}
yy242:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy243;
	default:	goto yy98;
	}
yy243:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy244;
	default:	goto yy98;
	}
yy244:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy245;
	}
yy245:
#line 127 "bt_lexer.re"
	{ TOKENIZE(BTT_HFLOAT)   }
#line 3335 "bt_lexer.cpp"
yy246:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy255;
	default:	goto yy98;
	}
yy247:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy251;
	default:	goto yy98;
	}
yy248:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy249;
	default:	goto yy98;
	}
yy249:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy250;
	}
yy250:
#line 148 "bt_lexer.re"
	{ TOKENIZE(BTT_FOR)      }
#line 3425 "bt_lexer.cpp"
yy251:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy252;
	default:	goto yy98;
	}
yy252:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy253;
	default:	goto yy98;
	}
yy253:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy254;
	}
yy254:
#line 128 "bt_lexer.re"
	{ TOKENIZE(BTT_FLOAT)    }
#line 3509 "bt_lexer.cpp"
yy255:
	yych = *++this->_cursor;
	switch (yych) {
	case 's':	goto yy256;
	default:	goto yy98;
	}
yy256:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy257;
	default:	goto yy98;
	}
yy257:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy258;
	}
yy258:
#line 158 "bt_lexer.re"
	{ TOKENIZE(BTT_FALSE)    }
#line 3593 "bt_lexer.cpp"
yy259:
	yych = *++this->_cursor;
	switch (yych) {
	case 's':	goto yy264;
	default:	goto yy98;
	}
yy260:
	yych = *++this->_cursor;
	switch (yych) {
	case 'u':	goto yy261;
	default:	goto yy98;
	}
yy261:
	yych = *++this->_cursor;
	switch (yych) {
	case 'm':	goto yy262;
	default:	goto yy98;
	}
yy262:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy263;
	}
yy263:
#line 142 "bt_lexer.re"
	{ TOKENIZE(BTT_ENUM)     }
#line 3683 "bt_lexer.cpp"
yy264:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy265;
	default:	goto yy98;
	}
yy265:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy266;
	}
yy266:
#line 150 "bt_lexer.re"
	{ TOKENIZE(BTT_ELSE)     }
#line 3761 "bt_lexer.cpp"
yy267:
	yych = *++this->_cursor;
	switch (yych) {
	case 'f':	goto yy275;
	default:	goto yy98;
	}
yy268:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	case 'u':	goto yy270;
	default:	goto yy269;
	}
yy269:
#line 153 "bt_lexer.re"
	{ TOKENIZE(BTT_DO)       }
#line 3839 "bt_lexer.cpp"
yy270:
	yych = *++this->_cursor;
	switch (yych) {
	case 'b':	goto yy271;
	default:	goto yy98;
	}
yy271:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy272;
	default:	goto yy98;
	}
yy272:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy273;
	default:	goto yy98;
	}
yy273:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy274;
	}
yy274:
#line 129 "bt_lexer.re"
	{ TOKENIZE(BTT_DOUBLE)   }
#line 3929 "bt_lexer.cpp"
yy275:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy276;
	default:	goto yy98;
	}
yy276:
	yych = *++this->_cursor;
	switch (yych) {
	case 'u':	goto yy277;
	default:	goto yy98;
	}
yy277:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy278;
	default:	goto yy98;
	}
yy278:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy279;
	default:	goto yy98;
	}
yy279:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy280;
	}
yy280:
#line 147 "bt_lexer.re"
	{ TOKENIZE(BTT_DEFAULT)  }
#line 4025 "bt_lexer.cpp"
yy281:
	yych = *++this->_cursor;
	switch (yych) {
	case 's':	goto yy297;
	default:	goto yy98;
	}
yy282:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy294;
	default:	goto yy98;
	}
yy283:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy284;
	default:	goto yy98;
	}
yy284:
	yych = *++this->_cursor;
	switch (yych) {
	case 's':	goto yy285;
	case 't':	goto yy286;
	default:	goto yy98;
	}
yy285:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy292;
	default:	goto yy98;
	}
yy286:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy287;
	default:	goto yy98;
	}
yy287:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy288;
	default:	goto yy98;
	}
yy288:
	yych = *++this->_cursor;
	switch (yych) {
	case 'u':	goto yy289;
	default:	goto yy98;
	}
yy289:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy290;
	default:	goto yy98;
	}
yy290:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy291;
	}
yy291:
#line 139 "bt_lexer.re"
	{ TOKENIZE(BTT_CONTINUE) }
#line 4152 "bt_lexer.cpp"
yy292:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy293;
	}
yy293:
#line 136 "bt_lexer.re"
	{ TOKENIZE(BTT_CONST)    }
#line 4224 "bt_lexer.cpp"
yy294:
	yych = *++this->_cursor;
	switch (yych) {
	case 'r':	goto yy295;
	default:	goto yy98;
	}
yy295:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy296;
	}
yy296:
#line 117 "bt_lexer.re"
	{ TOKENIZE(BTT_CHAR)     }
#line 4302 "bt_lexer.cpp"
yy297:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy298;
	default:	goto yy98;
	}
yy298:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy299;
	}
yy299:
#line 146 "bt_lexer.re"
	{ TOKENIZE(BTT_CASE)     }
#line 4380 "bt_lexer.cpp"
yy300:
	yych = *++this->_cursor;
	switch (yych) {
	case 'o':	goto yy310;
	default:	goto yy98;
	}
yy301:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy306;
	default:	goto yy98;
	}
yy302:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy303;
	default:	goto yy98;
	}
yy303:
	yych = *++this->_cursor;
	switch (yych) {
	case 'e':	goto yy304;
	default:	goto yy98;
	}
yy304:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy305;
	}
yy305:
#line 118 "bt_lexer.re"
	{ TOKENIZE(BTT_BYTE)     }
#line 4476 "bt_lexer.cpp"
yy306:
	yych = *++this->_cursor;
	switch (yych) {
	case 'a':	goto yy307;
	default:	goto yy98;
	}
yy307:
	yych = *++this->_cursor;
	switch (yych) {
	case 'k':	goto yy308;
	default:	goto yy98;
	}
yy308:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy309;
	}
yy309:
#line 138 "bt_lexer.re"
	{ TOKENIZE(BTT_BREAK)    }
#line 4560 "bt_lexer.cpp"
yy310:
	yych = *++this->_cursor;
	switch (yych) {
	case 'l':	goto yy311;
	default:	goto yy98;
	}
yy311:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy312;
	}
yy312:
#line 113 "bt_lexer.re"
	{ TOKENIZE(BTT_BOOL)     }
#line 4638 "bt_lexer.cpp"
yy313:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy314;
	case 'u':	goto yy315;
	default:	goto yy98;
	}
yy314:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy320;
	default:	goto yy98;
	}
yy315:
	yych = *++this->_cursor;
	switch (yych) {
	case 'i':	goto yy316;
	default:	goto yy98;
	}
yy316:
	yych = *++this->_cursor;
	switch (yych) {
	case 'n':	goto yy317;
	default:	goto yy98;
	}
yy317:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy318;
	default:	goto yy98;
	}
yy318:
	yych = *++this->_cursor;
	switch (yych) {
	case '6':	goto yy319;
	default:	goto yy98;
	}
yy319:
	yych = *++this->_cursor;
	switch (yych) {
	case '4':	goto yy136;
	default:	goto yy98;
	}
yy320:
	yych = *++this->_cursor;
	switch (yych) {
	case 't':	goto yy321;
	default:	goto yy98;
	}
yy321:
	yych = *++this->_cursor;
	switch (yych) {
	case '6':	goto yy322;
	default:	goto yy98;
	}
yy322:
	yych = *++this->_cursor;
	switch (yych) {
	case '4':	goto yy223;
	default:	goto yy98;
	}
yy323:
	++this->_cursor;
#line 97 "bt_lexer.re"
	{ TOKENIZE(BTT_XOR_ASSIGN)    }
#line 4704 "bt_lexer.cpp"
yy325:
	yych = *++this->_cursor;
	switch (yych) {
	case 'R':	goto yy326;
	default:	goto yy98;
	}
yy326:
	yych = *++this->_cursor;
	switch (yych) {
	case 'D':	goto yy132;
	default:	goto yy98;
	}
yy327:
	yych = *++this->_cursor;
	switch (yych) {
	case 'Y':	goto yy347;
	default:	goto yy98;
	}
yy328:
	yych = *++this->_cursor;
	switch (yych) {
	case 'H':	goto yy345;
	default:	goto yy98;
	}
yy329:
	yych = *++this->_cursor;
	switch (yych) {
	case 'N':	goto yy340;
	default:	goto yy98;
	}
yy330:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy338;
	default:	goto yy98;
	}
yy331:
	yych = *++this->_cursor;
	switch (yych) {
	case 'U':	goto yy336;
	default:	goto yy98;
	}
yy332:
	yych = *++this->_cursor;
	switch (yych) {
	case 'H':	goto yy333;
	default:	goto yy98;
	}
yy333:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy334;
	default:	goto yy98;
	}
yy334:
	yych = *++this->_cursor;
	switch (yych) {
	case 'R':	goto yy335;
	default:	goto yy98;
	}
yy335:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy132;
	default:	goto yy98;
	}
yy336:
	yych = *++this->_cursor;
	switch (yych) {
	case 'A':	goto yy337;
	default:	goto yy98;
	}
yy337:
	yych = *++this->_cursor;
	switch (yych) {
	case 'D':	goto yy136;
	default:	goto yy98;
	}
yy338:
	yych = *++this->_cursor;
	switch (yych) {
	case 'N':	goto yy339;
	default:	goto yy98;
	}
yy339:
	yych = *++this->_cursor;
	switch (yych) {
	case 'G':	goto yy151;
	default:	goto yy98;
	}
yy340:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy341;
	default:	goto yy98;
	}
yy341:
	yych = *++this->_cursor;
	switch (yych) {
	case '0':
	case '2':
	case '4':
	case '5':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	case '1':	goto yy342;
	case '3':	goto yy343;
	case '6':	goto yy344;
	default:	goto yy152;
	}
yy342:
	yych = *++this->_cursor;
	switch (yych) {
	case '6':	goto yy132;
	default:	goto yy98;
	}
yy343:
	yych = *++this->_cursor;
	switch (yych) {
	case '2':	goto yy151;
	default:	goto yy98;
	}
yy344:
	yych = *++this->_cursor;
	switch (yych) {
	case '4':	goto yy136;
	default:	goto yy98;
	}
yy345:
	yych = *++this->_cursor;
	switch (yych) {
	case 'A':	goto yy346;
	default:	goto yy98;
	}
yy346:
	yych = *++this->_cursor;
	switch (yych) {
	case 'R':	goto yy160;
	default:	goto yy98;
	}
yy347:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy348;
	default:	goto yy98;
	}
yy348:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy164;
	default:	goto yy98;
	}
yy349:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy350;
	default:	goto yy98;
	}
yy350:
	yych = *++this->_cursor;
	switch (yych) {
	case 'R':	goto yy351;
	default:	goto yy98;
	}
yy351:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy213;
	default:	goto yy98;
	}
yy352:
	yych = *++this->_cursor;
	switch (yych) {
	case 'A':	goto yy356;
	default:	goto yy98;
	}
yy353:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy354;
	default:	goto yy98;
	}
yy354:
	yych = *++this->_cursor;
	switch (yych) {
	case 'R':	goto yy355;
	default:	goto yy98;
	}
yy355:
	yych = *++this->_cursor;
	switch (yych) {
	case 'D':	goto yy136;
	default:	goto yy98;
	}
yy356:
	yych = *++this->_cursor;
	switch (yych) {
	case 'D':	goto yy223;
	default:	goto yy98;
	}
yy357:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy358;
	default:	goto yy98;
	}
yy358:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy359;
	default:	goto yy98;
	}
yy359:
	yych = *++this->_cursor;
	switch (yych) {
	case 'I':	goto yy360;
	default:	goto yy98;
	}
yy360:
	yych = *++this->_cursor;
	switch (yych) {
	case 'M':	goto yy361;
	default:	goto yy98;
	}
yy361:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy362;
	default:	goto yy98;
	}
yy362:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy363;
	}
yy363:
#line 133 "bt_lexer.re"
	{ TOKENIZE(BTT_OLETIME)  }
#line 5060 "bt_lexer.cpp"
yy364:
	++this->_cursor;
	yych = *this->_cursor;
yy365:
	switch (yych) {
	case '"':	goto yy368;
	default:	goto yy364;
	}
yy366:
	yych = *++this->_cursor;
	switch (yych) {
	case 'N':	goto yy367;
	default:	goto yy98;
	}
yy367:
	yych = *++this->_cursor;
	switch (yych) {
	case 'G':	goto yy231;
	default:	goto yy98;
	}
yy368:
	++this->_cursor;
#line 165 "bt_lexer.re"
	{ TOKENIZE_STRING_LITERAL(BTT_LITERAL_STRING) }
#line 5085 "bt_lexer.cpp"
yy370:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy371;
	default:	goto yy98;
	}
yy371:
	yych = *++this->_cursor;
	switch (yych) {
	case '0':
	case '2':
	case '4':
	case '5':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	case '1':	goto yy372;
	case '3':	goto yy373;
	case '6':	goto yy374;
	default:	goto yy232;
	}
yy372:
	yych = *++this->_cursor;
	switch (yych) {
	case '6':	goto yy213;
	default:	goto yy98;
	}
yy373:
	yych = *++this->_cursor;
	switch (yych) {
	case '2':	goto yy231;
	default:	goto yy98;
	}
yy374:
	yych = *++this->_cursor;
	switch (yych) {
	case '4':	goto yy223;
	default:	goto yy98;
	}
yy375:
	yych = *++this->_cursor;
	switch (yych) {
	case 'L':	goto yy376;
	default:	goto yy98;
	}
yy376:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy377;
	default:	goto yy98;
	}
yy377:
	yych = *++this->_cursor;
	switch (yych) {
	case 'A':	goto yy378;
	default:	goto yy98;
	}
yy378:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy244;
	default:	goto yy98;
	}
yy379:
	yych = *++this->_cursor;
	switch (yych) {
	case 'L':	goto yy383;
	default:	goto yy98;
	}
yy380:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy381;
	default:	goto yy98;
	}
yy381:
	yych = *++this->_cursor;
	switch (yych) {
	case 'A':	goto yy382;
	default:	goto yy98;
	}
yy382:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy253;
	default:	goto yy98;
	}
yy383:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy384;
	default:	goto yy98;
	}
yy384:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy385;
	default:	goto yy98;
	}
yy385:
	yych = *++this->_cursor;
	switch (yych) {
	case 'I':	goto yy386;
	default:	goto yy98;
	}
yy386:
	yych = *++this->_cursor;
	switch (yych) {
	case 'M':	goto yy387;
	default:	goto yy98;
	}
yy387:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy388;
	default:	goto yy98;
	}
yy388:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy389;
	}
yy389:
#line 134 "bt_lexer.re"
	{ TOKENIZE(BTT_FILETIME) }
#line 5327 "bt_lexer.cpp"
yy390:
	yych = *++this->_cursor;
	switch (yych) {
	case 'S':	goto yy395;
	case 'U':	goto yy394;
	default:	goto yy98;
	}
yy391:
	yych = *++this->_cursor;
	switch (yych) {
	case 'O':	goto yy392;
	default:	goto yy98;
	}
yy392:
	yych = *++this->_cursor;
	switch (yych) {
	case 'R':	goto yy393;
	default:	goto yy98;
	}
yy393:
	yych = *++this->_cursor;
	switch (yych) {
	case 'D':	goto yy151;
	default:	goto yy98;
	}
yy394:
	yych = *++this->_cursor;
	switch (yych) {
	case 'B':	goto yy406;
	default:	goto yy98;
	}
yy395:
	yych = *++this->_cursor;
	switch (yych) {
	case 'D':	goto yy396;
	case 'T':	goto yy397;
	default:	goto yy98;
	}
yy396:
	yych = *++this->_cursor;
	switch (yych) {
	case 'A':	goto yy402;
	default:	goto yy98;
	}
yy397:
	yych = *++this->_cursor;
	switch (yych) {
	case 'I':	goto yy398;
	default:	goto yy98;
	}
yy398:
	yych = *++this->_cursor;
	switch (yych) {
	case 'M':	goto yy399;
	default:	goto yy98;
	}
yy399:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy400;
	default:	goto yy98;
	}
yy400:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy401;
	}
yy401:
#line 132 "bt_lexer.re"
	{ TOKENIZE(BTT_DOSTIME)  }
#line 5461 "bt_lexer.cpp"
yy402:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy403;
	default:	goto yy98;
	}
yy403:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy404;
	default:	goto yy98;
	}
yy404:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy405;
	}
yy405:
#line 131 "bt_lexer.re"
	{ TOKENIZE(BTT_DOSDATE)  }
#line 5545 "bt_lexer.cpp"
yy406:
	yych = *++this->_cursor;
	switch (yych) {
	case 'L':	goto yy407;
	default:	goto yy98;
	}
yy407:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy273;
	default:	goto yy98;
	}
yy408:
	yych = *++this->_cursor;
	switch (yych) {
	case 'A':	goto yy409;
	default:	goto yy98;
	}
yy409:
	yych = *++this->_cursor;
	switch (yych) {
	case 'R':	goto yy295;
	default:	goto yy98;
	}
yy410:
	yych = *++this->_cursor;
	switch (yych) {
	case 'T':	goto yy411;
	default:	goto yy98;
	}
yy411:
	yych = *++this->_cursor;
	switch (yych) {
	case 'E':	goto yy304;
	default:	goto yy98;
	}
yy412:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy416;
	default:	goto yy413;
	}
yy413:
#line 110 "bt_lexer.re"
	{ TOKENIZE(BTT_LSR) }
#line 5591 "bt_lexer.cpp"
yy414:
	++this->_cursor;
#line 89 "bt_lexer.re"
	{ TOKENIZE(BTT_GE) }
#line 5596 "bt_lexer.cpp"
yy416:
	++this->_cursor;
#line 99 "bt_lexer.re"
	{ TOKENIZE(BTT_RS_ASSIGN)     }
#line 5601 "bt_lexer.cpp"
yy418:
	++this->_cursor;
#line 84 "bt_lexer.re"
	{ TOKENIZE(BTT_EQ) }
#line 5606 "bt_lexer.cpp"
yy420:
	++this->_cursor;
	switch ((yych = *this->_cursor)) {
	case '=':	goto yy424;
	default:	goto yy421;
	}
yy421:
#line 109 "bt_lexer.re"
	{ TOKENIZE(BTT_LSL) }
#line 5616 "bt_lexer.cpp"
yy422:
	++this->_cursor;
#line 88 "bt_lexer.re"
	{ TOKENIZE(BTT_LE) }
#line 5621 "bt_lexer.cpp"
yy424:
	++this->_cursor;
#line 98 "bt_lexer.re"
	{ TOKENIZE(BTT_LS_ASSIGN)     }
#line 5626 "bt_lexer.cpp"
yy426:
	++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '.':	goto yy428;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy426;
	default:	goto yy36;
	}
yy428:
	++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy428;
	default:	goto yy430;
	}
yy430:
#line 161 "bt_lexer.re"
	{ TOKENIZE(BTT_LITERAL_REAL)                  }
#line 5663 "bt_lexer.cpp"
yy431:
	yych = *++this->_cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy437;
	default:	goto yy432;
	}
yy432:
	this->_cursor = this->_marker;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy32;
	case 2: 	goto yy34;
	default:	goto yy50;
	}
yy433:
	yyaccept = 2;
	this->_marker = ++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '.':	goto yy428;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy433;
	case '8':
	case '9':	goto yy435;
	default:	goto yy34;
	}
yy435:
	++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '.':	goto yy428;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy435;
	default:	goto yy432;
	}
yy437:
	++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy437;
	default:	goto yy439;
	}
yy439:
#line 164 "bt_lexer.re"
	{ TOKENIZE(BTT_LITERAL_HEX)                   }
#line 5765 "bt_lexer.cpp"
yy440:
	++this->_cursor;
#line 94 "bt_lexer.re"
	{ TOKENIZE(BTT_DIV_ASSIGN)    }
#line 5770 "bt_lexer.cpp"
yy442:
	++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '*':	goto yy447;
	default:	goto yy442;
	}
yy444:
	++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '\n':	goto yy446;
	default:	goto yy444;
	}
yy446:
	yych = *++this->_cursor;
	goto yy9;
yy447:
	++this->_cursor;
	yych = *this->_cursor;
	switch (yych) {
	case '/':	goto yy448;
	default:	goto yy442;
	}
yy448:
	yych = *++this->_cursor;
	goto yy7;
yy449:
	++this->_cursor;
#line 102 "bt_lexer.re"
	{ TOKENIZE(BTT_DEC) }
#line 5802 "bt_lexer.cpp"
yy451:
	++this->_cursor;
#line 92 "bt_lexer.re"
	{ TOKENIZE(BTT_SUB_ASSIGN)    }
#line 5807 "bt_lexer.cpp"
yy453:
	++this->_cursor;
#line 101 "bt_lexer.re"
	{ TOKENIZE(BTT_INC) }
#line 5812 "bt_lexer.cpp"
yy455:
	++this->_cursor;
#line 91 "bt_lexer.re"
	{ TOKENIZE(BTT_ADD_ASSIGN)    }
#line 5817 "bt_lexer.cpp"
yy457:
	++this->_cursor;
#line 93 "bt_lexer.re"
	{ TOKENIZE(BTT_MUL_ASSIGN)    }
#line 5822 "bt_lexer.cpp"
yy459:
	++this->_cursor;
#line 95 "bt_lexer.re"
	{ TOKENIZE(BTT_AND_ASSIGN)    }
#line 5827 "bt_lexer.cpp"
yy461:
	++this->_cursor;
#line 80 "bt_lexer.re"
	{ TOKENIZE(BTT_LOG_AND) }
#line 5832 "bt_lexer.cpp"
yy463:
	++this->_cursor;
#line 85 "bt_lexer.re"
	{ TOKENIZE(BTT_NE) }
#line 5837 "bt_lexer.cpp"
yy465:
	++this->_cursor;
	yych = *this->_cursor;
yy466:
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy465;
	default:	goto yy7;
	}
}
#line 168 "bt_lexer.re"

    }

    return tokens;
}
 
