#define BTT_O_ROUND                          1
#define BTT_C_ROUND                          2
#define BTT_COMMA                            3
#define BTT_VOID                             4
#define BTT_BIN_AND                          5
#define BTT_TYPEDEF                          6
#define BTT_SEMICOLON                        7
#define BTT_STRUCT                           8
#define BTT_O_CURLY                          9
#define BTT_C_CURLY                         10
#define BTT_UNION                           11
#define BTT_ENUM                            12
#define BTT_LT                              13
#define BTT_GT                              14
#define BTT_CONST                           15
#define BTT_LOCAL                           16
#define BTT_ASSIGN                          17
#define BTT_COLON                           18
#define BTT_O_SQUARE                        19
#define BTT_C_SQUARE                        20
#define BTT_IDENTIFIER                      21
#define BTT_BOOL                            22
#define BTT_UNSIGNED                        23
#define BTT_SIGNED                          24
#define BTT_WSTRING                         25
#define BTT_STRING                          26
#define BTT_CHAR                            27
#define BTT_WCHAR                           28
#define BTT_TIME                            29
#define BTT_DOSDATE                         30
#define BTT_DOSTIME                         31
#define BTT_OLETIME                         32
#define BTT_FILETIME                        33
#define BTT_BYTE                            34
#define BTT_UCHAR                           35
#define BTT_UBYTE                           36
#define BTT_SHORT                           37
#define BTT_USHORT                          38
#define BTT_INT32                           39
#define BTT_UINT32                          40
#define BTT_INT64                           41
#define BTT_UINT64                          42
#define BTT_HFLOAT                          43
#define BTT_FLOAT                           44
#define BTT_DOUBLE                          45
#define BTT_IF                              46
#define BTT_ELSE                            47
#define BTT_WHILE                           48
#define BTT_FOR                             49
#define BTT_DO                              50
#define BTT_SWITCH                          51
#define BTT_BREAK                           52
#define BTT_CONTINUE                        53
#define BTT_RETURN                          54
#define BTT_CASE                            55
#define BTT_DEFAULT                         56
#define BTT_ADD_ASSIGN                      57
#define BTT_SUB_ASSIGN                      58
#define BTT_MUL_ASSIGN                      59
#define BTT_DIV_ASSIGN                      60
#define BTT_XOR_ASSIGN                      61
#define BTT_AND_ASSIGN                      62
#define BTT_OR_ASSIGN                       63
#define BTT_LS_ASSIGN                       64
#define BTT_RS_ASSIGN                       65
#define BTT_QUESTION                        66
#define BTT_LOG_OR                          67
#define BTT_LOG_AND                         68
#define BTT_BIN_OR                          69
#define BTT_BIN_XOR                         70
#define BTT_EQ                              71
#define BTT_NE                              72
#define BTT_LE                              73
#define BTT_GE                              74
#define BTT_LSL                             75
#define BTT_LSR                             76
#define BTT_ADD                             77
#define BTT_SUB                             78
#define BTT_MUL                             79
#define BTT_DIV                             80
#define BTT_MOD                             81
#define BTT_LOG_NOT                         82
#define BTT_BIN_NOT                         83
#define BTT_INC                             84
#define BTT_DEC                             85
#define BTT_SIZEOF                          86
#define BTT_DOT                             87
#define BTT_LITERAL_STRING                  88
#define BTT_LITERAL_OCT                     89
#define BTT_LITERAL_DEC                     90
#define BTT_LITERAL_HEX                     91
#define BTT_LITERAL_REAL                    92
#define BTT_TRUE                            93
#define BTT_FALSE                           94
